### ISSUE TITLE
Undefined when initiating tns debug ios --emulator

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/nativescript-cli#1251]
https://groups.google.com/forum/#!topic/nativescript/d5Guyb1fjKU

# Error
Frontend client connected.
(wait about 10-30 seconds)
Command xcrun with arguments simctl launch -w 3607EE15-7B8D-46AE-9DE4-2526D5E91E1F undefined --nativescript-debug-brk failed with exit code 4. Error output:

 An error was encountered processing the command (domain=FBSOpenApplicationErrorDomain, code=4):

The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 4.)

# What does work
* Android tns debugs emulator
* Starting the app, then attaching with tns debug ios --emulator --start

**Comment by Fatme** [comment]
Hi @sitefinitysteve,

It turns out that this is a bug on our side with Xcode 7+. We're working on the fix which will be included in the next release. Till then you can switch your Xcode to 6.4 or older version.  Just run 
`sudo xcode-select -s /Applications/Xcode6.4.app/Contents/Developer/` or as you mentioned you can use `tns debug ios --emulator --start` command.

**Comment by sitefinitysteve** [comment]
Thanks! Sorry about the duplicate post... Figured it was an issue that required a ticket not just a groups post.

**Comment by muratcorlu** [comment]
Is that bug fixed?

**Comment by TheOriginalJosh** [comment]
Just an FYI for anyone in the future that has this problem. 

going to `Simulator > Reset Content and Settings ...` fixed this issue for me
