### ISSUE TITLE
CLI 1.5.0 builds produce different application compared from Xcode build

### ISSUE THREAD

**Issue by hshristov** [NativeScript/nativescript-cli#1257]
I have sample application that when built from CLI produce application that is missing some image. If I open platforms/ios Xcode project with Xcode 7.1 (7B91b) and build the project from Xcode the produced app runs as expected and I can see the missing image.

**Comment by hshristov** [comment]
One more note - not only my image is missing but status-bar is not white as set from Info.plist (which gets added as plugin)

**Comment by Mitko-Kerezov** [comment]
Closing this issue as it was resolved.
The sample application's missing image was in fact a `jpg` image and Xcode only supports `png` images. The fix for this was simply [converting the image to png fomat](https://github.com/NativeScript/sample-TelerikNEXT/pull/10).
The status bar problems were derived from an improper plugin.
