### ISSUE TITLE
TNS Doctor should check CocoaPods/Ruby version

### ISSUE THREAD

**Issue by burkeholland** [NativeScript/nativescript-cli#1294]
I noticed that Ruby can wreak absolute havoc on a project when using CocoaPods. The wrong version (< 2.0.0) will throw cryptic errors that make people feel sad.

It would be nice if TNS doctor could...

1) Detect existence of CocoaPods (Mac only of course)
2) Detect version of Ruby and warn if the version is known to be incompatible

**Comment by burkeholland** [comment]
Why can't I add a label to this issue? GitHubbing is hard.

**Comment by teobugslayer** [comment]
@burkeholland,

We generally avoid to deal with dependencies of dependencies, because once you start this way, there's no end. CocoaPods site clearly states that `CocoaPods is built with Ruby and is installable with the default Ruby available on OS X. We recommend you use the default ruby.` We cannot guarantee that we or our dependencies work on broken machines.

Otherwise, we check for CocoaPods existence: https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/doctor-service.ts#L49

**Comment by burkeholland** [comment]
Understood. However, let me provide the feedback that as a developer, I would have bailed on this endeavor and would have mentally blamed {N} out of ignorance. I'm convinced that our ability to smooth our the developer experience is paramount. Throwing cryptic errors about `sandbox-pod` and then expecting the developer to figure it out on their own is going to cause abandonment.

Maybe we could provide better error handling in the build where pods are added?

**Comment by hshristov** [comment]
`tns doctor` did not show me that I was missing pod. It throws exception that ANDROID_HOME is not set correctly although I was using `tns emulate ios`

**Comment by teobugslayer** [comment]
I agree that we must check whether CocoaPods works robustly. I disagree that checking for particular version of Ruby brings value, because there can be millions of others issues which prevents CocoaPods from working. Imho, a better approach is to add a dummy pod into a dummy project and see if everything works. But this may not be easily doable.

**Comment by teobugslayer** [comment]
@hshristov, this was fixed in https://github.com/NativeScript/nativescript-cli/commit/4834e800809e11ddc8d7c372f6974528d2ad2c41 and is included in the upcoming CLI 1.5.2 release.

**Comment by hshristov** [comment]
@teobugslayer, Great.

Thanks

**Comment by dtopuzov** [comment]
Now doctor get iOS runtime and build a project to check cocoapods.
