### ISSUE TITLE
key-store-alias-password option not accepting empty password

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/nativescript-cli#1311]
```bash
$ tns run android --release --key-store-password 123456 --key-store-alias my-key-alias --key-store-alias-password "" --key-store-path my-release-key.keystore
The option 'key-store-alias-password' requires non-empty value.
```

**Comment by ligaz** [comment]
This is limitation of the Java's `keytool` which does not accepts empty passwords. Here is the exact phrase from the [docs](http://docs.oracle.com/javase/7/docs/technotes/tools/windows/keytool.html):
```
... the password has the value argument, which must be at least 6 characters long.
```

**Comment by HugoAntares** [comment]
@ligaz I have this issue and I don't know how to overcome it.

I've coded a v2 in NativeScript and I'm currently trying to publish it. The problem is that the v1, from another dev company, coded in Cordova and didn't set any password for the _android.keystore_ 🙈

**How can I sign my app with an empty password ?** 😬
