### ISSUE TITLE
Application entry point file not found... when using livesync (android)

### ISSUE THREAD

**Issue by x4080** [NativeScript/nativescript-cli#1332]
TNS 1.5, my steps :
1. tns run android
2. multi tasking button, close application (to force cold boot)
3. cold boot, works ok
4. tns livesync android
5. multi tasking button, close application (to force cold boot)
6. Above error (...bootstrap js etc)

I think in 1.4 it works ok

Is it only me ? Thanks

EDIT : in 4.4.4 (nexus 7), but in 6.0 (nexus 5) no error

**Comment by x4080** [comment]
Found the problem :

@app.js, application.cssFile = "app.css"; // was using Nathanael Livesync plugin

should be application.cssFile = "./app.css";

**Comment by x4080** [comment]
I tried using tns build android and the error come back on android 4.4.4, I check the package.json in the app directory and it is already correct :

{
    "name": "tns-template-blank-ts",
    "main": "app.js",
    "version": "1.2.0",
    "author": "Telerik <support@telerik.com>",
    "description": "Nativescript blank-ts project template",
    "license": "BSD",
    "keywords": [
        "telerik",
        "mobile",
        "nativescript",
        "{N}",
        "tns",
        "appbuilder",
        "template"
    ],
    "repository": {
        "url": "https://github.com/NativeScript/NativeScript/commit/06ddbf133a1c022a9ec61dc442d7f7ce0841c915"
    }
}

**Comment by rosen-vladimirov** [comment]
Hi @x4080 ,
Please excuse us for somehow missing this case. Do you still have the problem? Can you send your application that reproduces the issue?

**Comment by x4080** [comment]
Yes sir, tns livesync android on 4.4, nexus 7 and genymotion.. Everything good for lollipop and marshmallow.

Strangely the work around is using --watch :)

**Comment by x4080** [comment]
Oh forgot, it happened when app open then we press the home button, then app error happened

**Comment by rosen-vladimirov** [comment]
Ok, I've reproduced the issue. Here's the description of the problem (writing it down so I'm sure I'll not forget it):
When using `tns livesync android` CLI moves all files inside fullsync directory (in `/data/loca/tmp/<app_id>`) and changes permissions of all files to 777 so the runtime will be able to work with them.
When the app is started, the runtime cheks if there's something in `/data/loca/tmp/<app_id>/fullsync/` dir and gets it inside the application. After that the runtime should remove the files inside fullsync dir. However it looks like CLI had not added write permissions to the directories (for example tns-core-modules). On most of the devices runtime has required privileges to delete the files in `/data/loca/tmp/<app_id>/fullsync/` dir, but on some of them, it cannot do this. That's why CLI is executing chmod of the files inside it. In Genymotion, the runtime cannot delete the files in case CLI's chmod is not successfull. 
So the real reason for the error is that CLI had not given write permissions on tns-core-modules (and possibly on all directories).

@x4080 thanks for the detailed steps to reproduce. The workaround is to use `tns run android` in order to fix your application on the device.

**Comment by x4080** [comment]
Thanks again, but I use tns livesync android --watch for workaround since tns run android will be too slow :)

But why is it happened only on 4.4 ?

**Comment by rosen-vladimirov** [comment]
Well, it could happen on various devices. When using Genymotion I've reproduced it on all devices, no mater which is the Android version.
