### ISSUE TITLE
can you make xml file changes trigger livesync's watch?

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#1350]
_From @ogremagi88 on December 14, 2015 23:58_

I am making changes to my xml file constantly.  However livesync doesn't restart/refresh the app.  I have to go to the js file, add a space somewhere and save the file to get livesync to pickup the changes.  This is really annoying.  Can you make it so that changes to the xml files also restart the app please?  Trying to build a UI with this workflow is quite painful.

_Copied from original issue: NativeScript/NativeScript#1253_

**Comment by ligaz** [comment]
Hey @ogremagi88,

As of version 1.5 of NativeScript CLI XML and CSS changes are applied without restarting the application. We have made this improvement exactly to make the process of building UI quicker. 

Can you please help us investigate this issue on your side by recording a video that demonstrates it or sharing a sample project that does not triggers the sync when XML file is changed?

**Comment by ogremagi88** [comment]
I had been running nativescript 1.5.1.  When I upgraded to 1.5.2, I noticed my tns-core-modules was still on 1.4.x for some reason.  I upgraded it to 1.5.x as well and can confirm that changes to the xml files are livesyncing correctly now!  So I believe the problem was related to mismatched versions.  Thanks and you may close this issue.

**Comment by ligaz** [comment]
Glad that everything works as expected. Happy holidays :christmas_tree: :santa: :snowman:
