### ISSUE TITLE
Webstorm Ubuntu .bash_profile

### ISSUE THREAD

**Issue by rhalff** [NativeScript/nativescript-cli#1358]
I've noticed the installer has created a `.bash_profile`

.bash_profile:

``` bash
###-tns-completion-start-###
if [ -f /home/rhalff/.tnsrc ]; then
    source /home/rhalff/.tnsrc
fi
###-tns-completion-end-###
```

Normally Ubuntu does not have a `.bash_profile` and will load `.bashrc`.

The problem with the above is the rest of the environment will not get loaded while `.bashrc` is not being sourced.

Adding something like `[[ -s ~/.bashrc ]] && source ~/.bashrc` to the file would accomplish that.

I mention Webstorm, because it's terminal will consider loading `.bash_profile` instead of `.bashrc` which made it suddenly not load my normal environment anymore (e.g. nvm etc)

**Comment by hdeshev** [comment]
Looking at resources like:
* http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html
* http://stackoverflow.com/a/416931

I think the correct script to modify here would be the init script for interactive shells i.e. `.bashrc`. Login shells usually have their `.profile`/`.bash_profile` scripts set up so that they dot-source `.bashrc`, so tns completions will continue to work for those shells as well.

It seems the latest version of the service installing completions modifies *all* shell init scripts:

* https://github.com/telerik/mobile-cli-lib/blob/b86451865b8a0caf11806f8ac8a1b87ab0393407/services/auto-completion-service.ts#L26-L35
* https://github.com/telerik/mobile-cli-lib/blob/b86451865b8a0caf11806f8ac8a1b87ab0393407/services/auto-completion-service.ts#L125

which seems incorrect. We should target `.bashrc` and `.zshrc` (if present) only.

**Comment by psnider** [comment]
I had a similar problem on Mac.

OS: Mac El Capitan 10.11.5
tns: v2.1.1
Cross-platform modules: v2.1.0

I just installed nativescript via npm install -g nativescript but ran into a set of odd problems, which seem to have been caused by the install script creating a .bash_profile, which resulted in my .profile being skipped.

I've used .profile on Mac because many programs assume .profile.

It also appears that both the android installation and the java installation (run under the control of the nativescript install) both use .profile as well, as these two lines were added to the end of my .profile:
```
export ANDROID_HOME=/usr/local/opt/android-sdk
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home
```

I was able to resolve my issues by adding the following to the top of my .bash_profile:
```
if [ -f /Users/peter/.profile ]; then
    source /Users/peter/.profile
fi
```
Copied from original issue: NativeScript/NativeScript#2506
