### ISSUE TITLE
"tns create MyAppName" is a zombie - creates directory and nothing more

### ISSUE THREAD

**Issue by mike-ense** [NativeScript/nativescript-cli#1380]
Hi,

Doing "tns create MyAppName" only creates the directory and then nothing more.

Find the strace attached: [strace.txt](https://github.com/NativeScript/nativescript-cli/files/81499/strace.txt).

Do you see any plausible reason for this?

$ cat /etc/debian_version says 7.2, and uname -a says Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.51-1 x86_64 GNU/Linux .

If I can debug this further please let me know.

Thanks,
Mike

**Comment by teobugslayer** [comment]
Hi, can you execute `tns create MyAppName --log trace > log.txt` and send me the file?

**Comment by mike-ense** [comment]
Done

**Comment by teobugslayer** [comment]
Hi mike, from the logs you've sent, it looks like you have not set up and configure the Android SDK. Without it, you won't be able to build your app for Android. Also note that developing for iOS is available  only when running NativeScript on a Mac because it needs Apple Xcode.

Please check our [set up guide for Linux](http://docs.nativescript.org/start/ns-setup-linux) how to configure your machine.

Furthermore, if you are behind a proxy, you may need to configure both NativeScript (described [here](https://github.com/NativeScript/nativescript-cli#configure-proxy-usage) and Java.

**Comment by mike-ense** [comment]
@teobugslayer , can you reproduce the problem by doing "export ANDROID_HOME=ABC; tns create testproject" ? :)

**Comment by mike-ense** [comment]
@teobugslayer  , wait - weird - neither of messing up ANDROID_HOME *nor* "mv /usr/bin/java /usr/bin/javao" has any effect. I guess those should have been sufficient to make {N} not be able to reach them. I wonder what then caused the previous zombification.

**Comment by enchev** [comment]
Cannot reproduce with latest
