### ISSUE TITLE
"tns create app" won't build on iOS

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/nativescript-cli#1439]
I created a new folder\app called "app" to test a plugin and burned like an hour trying to figureout why it the tns run ios --emulator command would fail with errorcode 65.

Simple fix was to rename the root folder to "testapp" and it all worked again

Replicated on a new seperate project, same results

(Android was okay)

**Comment by fealebenpae** [comment]
@sitefinitysteve: on iOS the name of the project is also the name of the application bundle that Xcode builds AND the binary inside it. So if you name your project `foo`, you'd get `foo.app` (the application bundle) and `foo.app/foo` (the application executable). Alongside the executable, the application bundle carries within the `app` folder which contains the JavaScript code of the application.

Now, if you name your project `app`, this will result in a bundle called `app.app` and when the Xcode linker tries to create the executable it will fail, because it will try to create the file `app.app/app` which is already a folder.

Android, on the other hand, has an entirely different project structure so the `app` clash is iOS-specific. Unless you really want your project to be named `app` it would be best to accept that `app` is a reserved name, as projects go.

@teobugslayer: can we somehow preclude users from naming the project `app` in the CLI?

**Comment by sitefinitysteve** [comment]
@fealebenpae Would be fine with a fail message where tns doesn't even create it unless it's not "app".  I realize it's fine on android, but to save the headache for others...

**Comment by teobugslayer** [comment]
i think it was documented somewhere and we used to earn about this name. On my phone now and cannot easily check the sources, will get with more information tomorrow.

**Comment by teobugslayer** [comment]
Indeed, when creating a project named `app`, we warn that

```
You cannot build applications named 'app' in Xcode. Consider creating a project with different name.
```

We allow this scenario for people who want to build only for Android.
