### ISSUE TITLE
node inspector javascript error getPropertyCSSValue in 1.5.2

### ISSUE THREAD

**Issue by FrancoisCamus** [NativeScript/nativescript-cli#1471]
In 1.5.2 i was getting the javascript error described here:
https://github.com/node-inspector/node-inspector/issues/695

In package.json, the dependency to node-inspector is still pointing to "https://github.com/NativeScript/node-inspector/tarball/v0.7.4.0" in 1.5.2.
It's been fixed in master branch: now pointing to "https://github.com/NativeScript/node-inspector/tarball/v0.7.4.1".

A workaround for people using 1.5.2 is to modify the nativescript\node_modules\node-inspector\front-end\treeoutline.js wherever nativescript is installed

```
TreeElement.prototype.isEventWithinDisclosureTriangle = function(event)
{
    // FIXME: We should not use getComputedStyle(). For that we need to get rid of using ::before for disclosure triangle. (http://webk.it/74446) 
    // var paddingLeftValue = window.getComputedStyle(this._listItemNode).getPropertyCSSValue("padding-left");
    // var computedLeftPadding = paddingLeftValue ? paddingLeftValue.getFloatValue(CSSPrimitiveValue.CSS_PX) : 0;
    // var left = this._listItemNode.totalOffsetLeft() + computedLeftPadding;
    // return event.pageX >= left && event.pageX <= left + this.arrowToggleWidth && this.hasChildren;

	var paddingLeftValue = window.getComputedStyle(this._listItemNode).getPropertyValue("padding-left");
    var computedLeftPadding = paddingLeftValue ? parseInt(paddingLeftValue) : 0;
    var left = this._listItemNode.totalOffsetLeft() + computedLeftPadding;
    return event.pageX >= left && event.pageX <= left + this.arrowToggleWidth && this.hasChildren;
}
```

I've commented out the old code.

Why do you need to fork node-inspector? I'm sure there is a good reason. Just for knowledge.

**Comment by rosen-vladimirov** [comment]
@FrancoisCamus 
We need to work with special version of node-inspector, that's why we've forked it. This version has dependencies to some C++ modules, which require Visual Studio tools (and a lot of other things) when installing the package on Windows. As we do not want to require Visual Studio when installing nativescript CLI, we have forked node-inspector and change the native dependencies (prebuilt them), so now you can install it without issues on a clean Windows machine. 
As you've said the issue has been resolved in master branch, can I close this issue?

**Comment by FrancoisCamus** [comment]
Yes indeed. Thanks for the explanation.

**Comment by rosen-vladimirov** [comment]
You are welcome :)
