### ISSUE TITLE
NativeScript Debugging with Android fails

### ISSUE THREAD

**Issue by rajarameshvarma** [NativeScript/nativescript-cli#1480]
I am trying to find out how to debug my app rather than just putting console.log statements.

I am using Visual Studio Code as my text editor on Windows 10  machine with Visual Studio Emulator for Android or Genymotion Emulator.

I tried to debug using Chrome as explained [here][1] and also tried using [NativeScript Extension for Visual Studio Code][2]

With debugging using NativeScript CLI, project successfully opens Chrome browser but throws a 404 error.

    tns debug android --debug-brk

[![Failed to load resource: the server responded with a status of 404][3]][3]

With Visual Studio Code extension, i receive this error:

[![Debug adapter process has terminated unexpectedly][4]][4]

and I see an error in the command prompt.
[![Cannot find module 'source-map'][5]][5]

I tried suggestions from [this][6] SO post, though this problem is with Chromium, but that did not help.

  [1]: https://docs.nativescript.org/runtimes/android/debug/debug-cli
  [2]: https://github.com/NativeScript/nativescript-vscode-extension
  [3]: http://i.stack.imgur.com/FUmn4.png
  [4]: http://i.stack.imgur.com/BEmb8.png
  [5]: http://i.stack.imgur.com/gzikY.png
  [6]: https://stackoverflow.com/questions/32515336/how-debug-nativescript-code

**Comment by Plamen5kov** [comment]
ping: @ivanbuhov @blagoev

**Comment by ivanbuhov** [comment]
I guess you have manually built the VSCode extension from its [repo](https://github.com/NativeScript/nativescript-vscode-extension). Make sure, you have executed `npm install` and `tsd install` before packaging and installing it.
However, I recommend installing the extension from the marketplace instead of manually building it. Currently, its live and you can install it by running `Install Extension` from Command Palette, and search for `NativeScript`. Do you see the error message with the extension, installed from the marketplace?

**Comment by rajarameshvarma** [comment]
@ivanbuhov Thank you for your response. Yes, I have installed it from Market Place this morning and everything is working except it is not able to launch the application. But I can attach the debugger to my emulator.

**Comment by ivanbuhov** [comment]
@rajarameshvarma Can you provide more information about the not working app launching. Which launch configuration do you use? What happens when you launch your app?

**Comment by rajarameshvarma** [comment]
I am exactly with this situation. https://github.com/NativeScript/nativescript-vscode-extension/issues/23
I think we can close this thread
