### ISSUE TITLE
Unable to load framework, doesn't seem to add Symbolic Links

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/nativescript-cli#1774]
[Structure](https://github.com/sitefinitysteve/nativescript-kiip/tree/240ba0a79bf70f266a37f67ff6fab048bbce926e/plugin/platforms/ios/KiipSDK.framework)
(Updated link to prev commit)

So when I do a tns plugin add ../plugin all that comes into the node_modules/nativescript-kiip folder is the Versions folder and the info.plist, not the symbolic link files.

Tried even just moving the file and headers out to the root, and running that, just more errors.

I was under the assumption framework files are supported (preferred method of delivery), no?

**Comment by xmlking** [comment]
I have same issue with my project working with Microsoft Band SDK.

Looking like Cordova guys had some workaround for NPM symbolic link limitation: 
https://taco.visualstudio.com/en-us/docs/tips-and-workarounds-ios-ios-plugin-symlink-fix-readme/
https://github.com/Microsoft/cordova-docs/blob/master/articles/tips-and-workarounds/ios/ios-plugin-symlink-fix/tips-and-workarounds-ios-ios-plugin-symlink-fix-readme.md

Hope to see fix for "tns add"

**Comment by ivanbuhov** [comment]
@sitefinitysteve It turns out that this is a `npm` issue. `npm` fails to move some symlinks on `npm install`. What Cordova has is a simple hook that recreates the symlinks before compile. Generally, you can add such a hook in your plugin with the help of [`nativescript-hook`](https://github.com/NativeScript/nativescript-hook) plugin but I recommend eliminating the symlinks from your framework before packing it and replacing it with its destination. Instead of having a symlink to the framework executable and the `Headers` folder in the root of your framework, replace them with the actual executable and `Headers` folder. This will eliminate the need of having a special hook doing a similar operation on every client machine.
Let me know if this doesn't work for you?

**Comment by sitefinitysteve** [comment]
Sure this sounds good :) 👍
