### ISSUE TITLE
tns doctor wont run

### ISSUE THREAD

**Issue by russellharrower** [NativeScript/nativescript-cli#1888]
I am wondering after following your easy set up guide why, tns doctor will not run on Mac OS X 10.11.5 the error I get is tns: command not found

**Comment by enchev** [comment]
Hey @russellharrower,

Do you get any errors? What's your NativeScript CLI version?

**Comment by russellharrower** [comment]
I am starting fresh, following the instructions on the readme.md

> OS X
> 
> On OS X systems, you can develop, build, and deploy NativeScript projects that target iOS and Android.
> Setup Script
> 
> To quickly set up your system for the latest NativeScript CLI, paste the following Ruby script in the Terminal and hit Enter:
> 
> sudo ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"

**Comment by rosen-vladimirov** [comment]
Hey @russellharrower ,
You can try following the instructions [here](http://docs.nativescript.org/start/quick-setup). Please note the ruby script will not install Node.js and NativeScript CLI on your machine. So I have a couple of questions that may help us find the problem: 
* Did you install Node.js?
* Did you execute `npm install -g nativescript`?

In case you have installed both Node.js and nativescript, but you are still unable to execute `tns doctor`, you might check if the installation path (you'll find it as a message somewhere at the end of `npm install -g nativescript` - check for "Installed at ...") is part of your PATH environment variable.

**Comment by SGissubel** [comment]
I am having this issue currently.  What is the resolution? 

my bash-profile looks like this:

`
# added by Anaconda3 4.3.0 installer
export PATH="/Users/stevengissubel/anaconda/bin:$PATH"
export PATH=$PATH:/usr/local/mysql/bin/mysql

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/usr/local/opt/node@8/bin:$PATH"
export PATH="/usr/local/opt/node@8/bin:$PATH"
`

My install returns the following:

> rb-mac-007:~ stevengissubel$ npm install -g nativescript

> nativescript@4.1.2 preuninstall /Users/stevengissubel/.npm-global/lib/node_modules/nativescript
> node preuninstall.js

/Users/stevengissubel/.npm-global/bin/tns -> /Users/stevengissubel/.npm-global/lib/node_modules/nativescript/bin/tns
/Users/stevengissubel/.npm-global/bin/nativescript -> /Users/stevengissubel/.npm-global/lib/node_modules/nativescript/bin/tns

> nativescript@4.1.2 postinstall /Users/stevengissubel/.npm-global/lib/node_modules/nativescript
> node postinstall.js

Autocompletion is already enabled

Installation successful. You are good to go. Connect with us on http://twitter.com/NativeScript.

You have successfully installed NativeScript CLI.
In order to create a new project, you can use:
tns create <app name>

To build your project locally you can use:
tns build <platform>

NOTE: Local builds require additional setup of your environment. You can find more information here: https://docs.nativescript.org/start/quick-setup


To build your project in the cloud you can use:
tns cloud build <platform>

NOTE: Cloud builds require Telerik account. You can find more information here: https://docs.nativescript.org/sidekick/intro/requirements


In case you want to experiment quickly with NativeScript, you can try the Playground: https://play.nativescript.org


In case you have any questions, you can check our forum: https://forum.nativescript.org and our public Slack channel: https://nativescriptcommunity.slack.com/

+ nativescript@4.1.2
updated 1 package in 4.921s
rb-mac-007:~ stevengissubel$ tns
-bash: tns: command not found
