### ISSUE TITLE
tns run ios --emulator

### ISSUE THREAD

**Issue by eliavmaman** [NativeScript/nativescript-cli#1940]
get this error:
```
nativescript-iqkeyboardmanager has Podfile and you don't have 
Cocoapods installed or it is not configured correctly. 
Please verify Cocoapods can work on your machine.
```

after that  i removed the nativescript-iqkeyboardmanager plugin and install it again.
still get that error.
What to do?

**Comment by NickIliev** [comment]
Hello @eliavmaman 

In order to use third-party libraries for iOS development (which your plugin is requiring) you should have [CocoaPods](https://cocoapods.org/)  dependency manager installed.

To install CocoaPods in your terminal run the following command
```
sudo gem install cocoapods
```

Also to check what version of CocoaPods you ar eusing you can run
```
pod --version
```
