### ISSUE TITLE
Add --watch option in build command

### ISSUE THREAD

**Issue by bekos** [NativeScript/nativescript-cli#1951]
My workflow:
I am using a docker to build a Nativescript project from the sources that are shared with my host machine. I run a Genymotion emulator on my host machine and when the `.apk` changes I have a watch script to install and launch it inside the Genymotion. 

The problem I have is that the build command cannot watch file for changes (I can setup a watcher myself but it would be more convenient if cli was supporting it) and the other, is that build time is too slow (around 3 min). Also, could be a way that in `--watch` mode have an "incremental" way to build the apk, in order to be faster?

Thanks

**Comment by bekos** [comment]
Updated my original description with the rationale :-)

**Comment by enchev** [comment]
Hey @bekos,

Can you provide more info why you need docker in your case? Are you trying to setup some CI environment? 

We've made `--watch` to speed up local development (livesync command) and we don't think that such option can fit easily in the build process. We definitely want to speed up the build process however and we will invest time in the upcoming {N} CLI versions for sure.

**Comment by bekos** [comment]
Hi @enchev. I have really big trouble installing and upgrading NS with Android SDK tools to some workstations in my company running Windows/Mac. Docker (Linux) seems the only solution.

I understand if `--watch` cannot fit, but any improvement is highly appreciated :-)
Feel free to close if this is not actionable. Thanks.

**Comment by hdeshev** [comment]
Hi @bekos,

I was thinking about this setup, and had an idea of running the `adb` bridge over TCP/IP. Theoretically, it should be possible to run an Android build environment in a docker image and forward `adb` TCP connections to your host, or rather its Genymotion emulator. This way a `tns run` or `tns livesync` command in the docker container should be able to deploy the app to the emulator running outside the container.

I tried to get something similar running here, but, unfortunately, my sysadmin skills failed me. I followed [this guide](https://dzone.com/articles/use-adb-over-wi-fi-without) to switching `adb` to TCP mode, and tried setting up a connection forward over SSH from another machine (just to test if the `tns` CLI tool would be able to use it). There's some good news though: `tns devices` seems to detect the device, but displays it as being offline.

I'm pretty sure it's possible to get this working, but it needs some more tinkering.

**Comment by hdeshev** [comment]
Well, I got it running over the weekend! I run a tiny VPS instance and I was able to use SSH forwards so that I can build my app on the remote machine and deploy it on an emulator running on my desktop machine. The same technique should work with docker/vagrant images!

So, the main trick is to forward port 5037 and kill your adb servers (I had to kill both my local and remote one). Details [here](http://www.jnchen.com/blog/2012/11/tunnelling-adb).

One thing that bit me is that either adb or tns tried to connect to another port when doing app livesyncs (`tns livesync android --watch`). In my case that was port 18181. I didn't investigate much, and just added another SSH reverse forward that exposed port 18181 in the same way I did for port 5037. Everything works pretty nice, livesyncing your app to an emulator running 2000 kilometers away. :)

**Comment by hdeshev** [comment]
I wanted to post a final clarification about the port forwarding solution above since it is superior to adding a `--watch` switch to `tns build`. A huge portion of the time building an apk is spent in running the gradle script which builds the app archive. We work around that by syncing just scripts to the device and avoid all the work the gradle script does. You can't do that for `tns build` though -- its output depends on running gradle by definition.

Closing this issue.

**Comment by bekos** [comment]
@hdeshev Thanks for the info! I will try it asap. Keep up the good work 👍
