### ISSUE TITLE
Livesync starts the app twice on iOS devices

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/nativescript-cli#1956]
1. Create an app and add ios platform and navigate to the app's folder
2. Deploy the app on the device and make sure it is not opened
3. Run `tns livesync`

Expected result: App is started and synced with current state
Actual result: Splash screen is opened, closed and opened once again

**Comment by dtopuzov** [comment]
Works for me with {N} 2.1.1

**Comment by slavchev** [comment]
ping @pkoleva @dtopuzov 

Can we close this issue?

**Comment by pkoleva** [comment]
Hey guys, would you please stop moving this issue as Ready for Test and have a look at it. It is still reproduced in 2.5 master. The issue reproduces when the app is already installed on the device.

**Comment by Plamen5kov** [comment]
fixed by: https://github.com/NativeScript/nativescript-cli/pull/2484

**Comment by pkoleva** [comment]
Issue still reproducible (3.0) with run command as well

**Comment by rosen-vladimirov** [comment]
As @Plamen5kov  described - the problem is with the GDB server on device - if the application is not runnning, calling `stopApplication` starts it and stops it after that. That causes the blink effect (double restart). As we cannot detect if application is currently running (and skip `stopApplication` in case it is not), we always call `stopApplication`. So I'm closing this issue as we cannot fix it.
