### ISSUE TITLE
My emulator does not load the app

### ISSUE THREAD

**Issue by Rolfi43** [NativeScript/nativescript-cli#2004]
![problema](https://cloud.githubusercontent.com/assets/21068916/17717722/39a0ca94-63d5-11e6-9e5b-ae5b55bf51c4.jpg)

When I start the command tns run android or tns run android --emulator start downloading that file but then stops and stops charging

Help me please

**Comment by dtopuzov** [comment]
What happens on the screenshot is: 
When you call "tns run android" it internally call "tns build android" and build android download gradle (it is required in order to build native android projects). If your download does not finish may be you have some network issues and you can not download gradle. 
Please get the url form your screenshot and try to download it (just to check your connection is ok).

If run hangs after download is complete then you should see some more logs, please add them.
In addition you can run any tns command with --log trace option to get more logs. 
For example: "tns run android --log trace".

Please add more logs.

**Comment by Rolfi43** [comment]
hello and thank you but I have it installed and added Gradle and its environment variables but continues to do the same and also already have added the path where you are gradle in my android study.

**Comment by dtopuzov** [comment]
Please run "tns run android --log trace" and send logs.

**Comment by Rolfi43** [comment]
when I run it with an open emulator I get the message downloading gradle2.10 and without emulator I get message
Spawn: C: \ Users \ Rodolfo \ AppData \ Local \ Android \ android-sdk \ tools \ emulator "-avd" "AVD_for_Nexus_4_by_Google"
execfile: C: \ Users \ Rodolfo \ AppData \ Local \ Android \ android-sdk \ platform-tools \ adb "devices" and keeps repeating the message execfile: C: \ Users \ Rodolfo \ AppData \ Local \ Android \ android -SDK \ platform-tools \ adb "devices"

**Comment by dtopuzov** [comment]
adb "devices" list all your devices. In this case it looks tns try to boot emulator with name "AVD_for_Nexus_4_by_Google" and wait until it is up and running. 
Unfortunately it hangs because most likely "AVD_for_Nexus_4_by_Google" is broken.

Run this from a terminal:
```
emulator -avd AVD_for_Nexus_4_by_Google
```
and see if it will boot. If something is wrong most likely you will have some error output from the command above.

**Comment by Rolfi43** [comment]
I'm sorry but it does not work what you told me the error remains the same

**Comment by Rolfi43** [comment]
I'm sorry but it does not work what you told me the error remains the same
