### ISSUE TITLE
Developing project on second machine

### ISSUE THREAD

**Issue by grasshoppermouse** [NativeScript/nativescript-cli#2126]
I setup my work iMac with nativescript, created a new project, and successfully launched the iOS emulator. I then setup my home iMac for nativescript and copied the project folder. When I try to launch the iOS emulator on my home iMac, I get this error:

```
iMac:ns-conference-app admin: tns run ios --emulator

Command xcrun with arguments simctl launch 1B06A134-C3EC-4578-A0F7-F4A3423B4A6E org.nativescript.nsconferenceapp failed with exit code 1. Error output:
 An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "org.nativescript.nsconferenceapp" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "org.nativescript.nsconferenceapp" is unknown to FrontBoard").
```

After googling, I'm guessing that some plists also need to be copied over? Any advice appreciated.

**Comment by tzraikov** [comment]
Hi @grasshoppermouse, this issue could happen when using Xcode 8 because the iOS simulator launches too slow. You have two options:
1. Start the simulator before launching the application
2. Modify the native project and choose the "Wait for executable to be launched" option by editing the project scheme. This approach is discussed [here](http://stackoverflow.com/questions/37939749/xcode-8-messages-template-application-error-on-ios-simulator)

**Comment by grasshoppermouse** [comment]
The first option worked great, thanks!

**Comment by cerniuk** [comment]
My issue is the opposite... if the launch happens too fast, the error occurs. It occurs less if I fully quit the simulator and let it launch from scratch in response to a debug session
