### ISSUE TITLE
Install Problems / Notes

### ISSUE THREAD

**Issue by Dillie-O** [NativeScript/nativescript-cli#2139]
Greetings team,

I've started digging into NativesScript after seeing a demo this weekend and I'm really excited by what I see. I went down the "Getting Started" path and I ran into a couple of hiccups along the way. I'm not sure if they are just nuances with newer configurations, or if maybe some updates need to be done for the entire process. Here's what I ran into and my solutions, hoping this might help others as well.

Configuration: I'm on a Late 2015 MacBook Pro that I upgraded to macOS Sierra (10.12) about a month ago. I run ZSH (oh-my-zsh) as my primary shell through iTerm2. I already had Xcode installed and it was updated to the latest version last month.

The installation script appeared to have run successfully, and I made sure that all the Android libraries were installed. However, since I was running ZSH, the path statements weren't added to my .zshrc startup profile, even though the auto-complete feature was and my basic .profile had the android paths in them. Manually updating this fixed the issue, but it might be worth detecting the shell and adding the path elsewhere.

After this I ran `tns doctor` and it said I was missing coccoapods and xcodeproject even though I know Xcode was installed. A little more digging showed that I had to update ruby to version 2.2+ (I was running 2.0) and then I had to subsequently rerun the installation of these gems (and the optional xcproj) manually. I also found out that I had to run cocopod setup/installer manually after the gem install, which the default setup script may be doing but I'm not sure.

Finally, and the most nuanced, was that after all of this my simple `tns run ios --emulator` command kept failing with an exit code 65, but after some digging the most appropriate in the console was the following

```
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
Referenced from: /usr/local/bin/bash
Reason: image not found
```

Not being a super "CLI guru" this one took a little digging. I tried a brew install/reinstall, I tried a postgres install/reinstall (some sources were pointing to this) with no luck. Finally, what worked was to manually download/configure/make/install an older version of readline as outlined here:

http://stackoverflow.com/questions/39926599/need-old-version-of-readline-for-activator

Once I did this, and restarted the terminal, I was aces and can work on my grocery store 8^D

There's a pretty good chance that I have a couple of nuances to my own MBP environment that could have caused some of these issues, but it may be worth checking into (especially version things) that the doctor script didn't seem to pick up. Overall I'm up and running with "Hello World" much faster than I was with Xamarin, so I'm excited to see what happens when I start building things out.

Hopefully this helps. Feel free to reply if you need more configuration/feedback details.

**Comment by dtopuzov** [comment]
@Dillie-O thanks for detailed report. 
We are aware of some of the issues and getting started is a bit hard with macOS Sierra.
With ElCapitan it is not required to install Ruby 2.2 in order to get CocoaPods running.

CocoaPods and xcodeproject  does not come with Xcode and they should be installed additionally (we do this in the setup script), but unfortunately installation fails on macOS Sierra because of Ruby version.

We will try to fix the script and get macOS Sierra users happy.

Zsh is another issue that may be need to be handled in the CLI code (not in setup script).

Once again, thanks for report, we will try to fix the issues as soon as we have resources.

Btw, setup scripts are available here: https://github.com/NativeScript/nativescript-cli/tree/master/setup and we will be happy to receive pull requests.
