### ISSUE TITLE
Building with --compileSdk 19 fails

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/nativescript-cli#2169]
**Steps to reproduce:**
1. Create an app 
2. run `tns build android --compileSdk 19`
**Expected result:** 
Build is successful
**Actual result:** 
`> Could not resolve all dependencies for configuration ':_F0DebugCompile'.`
   `> Could not find com.android.support:design:19.1.0.`

**Comment by slavchev** [comment]
The problem is caused by the fact that the project template uses the specified version, in this case `19`, for three different (`android-support`, `appcompat` and `design`) libraries each of which comes with its own versioning. In this scenario `design` library starts from `22.2.0` and doesn't have `19.1.0` version.

According [the docs](https://docs.nativescript.org/runtimes/android/requirements) the minimum supported version is 17 which currently we don't fulfill. One option is to update the docs so that the minimum supported version becomes `21`.

**Comment by prantikv** [comment]
@slavchev If I understand this correctly, the lowest version of android that we can build for is lollypop (API 21) and not jellybean (API 17)?
