### ISSUE TITLE
The tns debug ios command hangs on launch screen 

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#2225]
The `tns debug ios` command hangs on the launch screen and the *Resources* tab does not fill in with the files of the application

Setup:
Xcode 8.1
{N} CLI 2.4.0

**Comment by vchimev** [comment]
It turned out that the python package **six** is required in order **LLDB** to operate properly. It could be installed as follows:
```shell
pip install six
```

**Comment by vchimev** [comment]
Perhaps we need to add verification of the **six** package in the `tns doctor`, as well as include it into the setup script?

@KristinaKoeva, @jasssonpet, @rosen-vladimirov, others, what do you think?

**Comment by rosen-vladimirov** [comment]
In case there's no other way of bypassing the missing `six` python package, we should definitely add it to doctor. 
Does this occur only when XCode 8.x is used?

**Comment by jasssonpet** [comment]
The six module is installed by default in `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python`. This should only happen if the user is using a custom Python version.

**Comment by tsonevn** [comment]
Can we add this package to setup script?

**Comment by toddanglin** [comment]
Just encountered the new warning about 'six' package with 3.0 RC. Never had a problem (as far as I know) in the past. Wondering if the new check is accurate...

If the check is accurate and 'six' is missing, suggest that the official documentation page provide info for installing/configuring this correctly. By default on Mac, the `pip` command is not available.

**Comment by pkoleva** [comment]
Hey, @toddanglin, we encountered an issue with debugging on iOS on our machines, where we have custom python installed with brew, so we proposed to have such a check. By default in the system python in OSX 'six' is installed, so you don't have to do anything to get it. 

About pip - it isn't installed in most of python versions, so we expect people that installed custom python to be aware of how to get pip and use it since this is the most commonly used package manager. 

About the accuracy of out check in `tns doctor` could you verify you have 'six' installed and you still get the message you don't by running:
```
python
import six
```
and then run `tns doctor`.

Thanks :)

**Comment by toddanglin** [comment]
Well...as a result of this message, I installed python via brew and ran `pip install six`...which made the `tns doctor` warning go away. :)

So...if you're suggesting OS X should not need to perform these steps, perhaps there is some way to improve the check so that the warning is not displayed on systems that do not need to run `pip install six`? If that's not possible, we should at least document this nuance in the "official documentation" page that the CLI opens when `tns doctor` finds a problem.

**Comment by dtopuzov** [comment]
Hi @toddanglin 

Missing `six` may cause issues when running or on some real iOS devices (it looks it is device/iOS version dependent), but unfortunately we can't predict what iOS device user can connect to its mac host, so we explicitly check if `six` is available.

By default it is available, so we don't expect a lot of cases when users will hit this warning.
However may be we should add some notes to documentation for debugging.

**Comment by toddanglin** [comment]
Yeah, at the very least, improving the `tns doctor` detail OR the documentation that the CLI links to when there are installation errors would help. 👍
