### ISSUE TITLE
When using Node 6.9.1 I Receive the error "TypeError: Cannot read property 'LayoutParams' of undefined"

### ISSUE THREAD

**Issue by victorhugom** [NativeScript/nativescript-cli#2322]
When using the latest “LTS” node the app does not run and I receive the following error.
`"TypeError: Cannot read property 'LayoutParams' of undefined"`

The error doesn't show with node v4.6.2

Platform: Windows 10
nativescript            2.4.1 
tns-core-modules  2.4.1
tns-android            2.4.1  
tns-ios                    2.4.0

**Comment by Plamen5kov** [comment]
Hi @victorhugom can you provide us the steps to reproduce, because I tried:
* npm install nativescript -g
* tns create app1 && cd app1
* tns platform add android
* tns run android
and couldn't manage to reproduce your problem. 
What operating system are you encountering this problem? Do you get the error at build-time or at runtime?

**Comment by PanayotCankov** [comment]
You need to update the tns-core-modules-widgets. It is a dependency of the tns-core-modules. Make sure that you don't have it twice somewhere in the node_modules.
