### ISSUE TITLE
Set different platform bundle identifiers

### ISSUE THREAD

**Issue by roblav96** [NativeScript/nativescript-cli#2336]
So we're updating our existing native apps with nativescript and each platform have their own bundle identifiers. I was wondering if something like this would be possible:
```json
	"nativescript": {
		"tns-android": {
			"id": "com.sandbox.android",
			"version": "2.4.1"
		},
		"tns-ios": {
			"id": "com.sandbox.ios",
			"version": "2.4.0"
		}
	},
```

**Comment by PanayotCankov** [comment]
It is not. We had similar problems and ended adding CI scripts that change the key in the package.json before publish.
This is related: https://github.com/NativeScript/NativeScript/issues/3157 If we alter the tooling to store values in the native projects rather than depending on the package.json the bundle id will be stored in the AndroidManifest.xml or the build.gradle and the Info.plist rather than the package.json in the root of the repo and will allow for the it to diverge.

**Comment by roblav96** [comment]
Well that's what I've been doing in the meantime. Although I can't use livereload doing this :/

**Comment by surdu** [comment]
This is required if you rewrite an existing application in NativeScript. I quite like @roblav96 idea, to have the id under runtime keys.

Other idea would be to have something like this:

```json
  "nativescript": {
    "id": {
      "android": "com.myapp.android",
      "ios": "com.myapp.ios"
    }
  }
```

I believe this way might be easier to maintain backwards compatibility.

**Comment by Pip3r4o** [comment]
@surdu the feature is under review, and will be merged in the next NativeScript version - https://github.com/NativeScript/nativescript-cli/pull/3120
