### ISSUE TITLE
code signing, provisioning and xcargs for Xcode 8 in CI environments

### ISSUE THREAD

**Issue by vbresults** [NativeScript/nativescript-cli#2354]
Proposing a `--xcargs` parameter for `tns build ios` that is passed through to xcodebuild/archive for various purposes, and so that builds can be done in a CI environment (without opening Xcode 8).

Found a way to do code signing in CI, which could be [passed as arguments](https://gist.github.com/vbresults/9da2b42e0fabf111a100e05c502aba98) `--provisioing-profile-specifier --codesign-identity --development-team-id` to `tns build ios` in Xcode 8.

Ping @hdeshev

**Comment by PanayotCankov** [comment]
@vbresults This fails should you have Cocoapods, the xcodebuild tries to sign the pod frameworks and attach the provisioning profiles, often failing due to app identifier mismatch.

Our CI sed-s the "PROVISIONING_PROFILE = <provisioning-profile-uuid>;" upon build in the "app/App_Resources/iOS/build.xcconfig" that is added to the app by the CLI. The next release will have an experimental option to the ios commands:
 - `tns prepare|run|build ios --provision` to list all eligible provisioning profiles
 - `tns prepare|run|build ios --provision <uuid or name>` to set Manual signing style in the Xcode project and provide the specified provisioning profile.
