### ISSUE TITLE
`tns init` fails, `ins init --force` produce invalid app

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2559]
Steps to reproduce:
`tns init --path MyApp`

Output:
```
 stderr: 
SyntaxError: Unexpected token n in JSON at position 4
    at Object.parse (native)
    at NodePackageManager.<anonymous> (/Users/topuzov/Git/nativescript-cli-tests/node_modules/nativescript/lib/node-package-manager.js:103:25)
    at next (native)
    at fulfilled (/Users/topuzov/Git/nativescript-cli-tests/node_modules/nativescript/lib/node-package-manager.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 1 }

```

Notes: 
`tns init --path MyApp --force` creates app, but without App Resources.
I think this command is useless, since no one complained it does not work without `--force` and it produce not build able app with `--force`.

**Comment by mnaughto** [comment]
FWIW, I tracked this down to here https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/init-service.ts#L109. In other places, the second argument to `$npm.view()` is a hash like `{json: true, versions: true}`, whereas here it just passes "versions", so the output of the subsequently invoked `npm view` command is not valid JSON.

**Comment by mnaughto** [comment]
I can open a pull request if that'd be useful, but I'm guessing a normal contributor to this project might have an easier time.

**Comment by yyosifov** [comment]
Hi,

@mnaughto You are right - this was one of the problems. I've set explicitly in the NPM View method to set `{ json: true }` always. Another error was that it seems like the NPM View response has changed as a structure and this alone didn't fix the problem. Now `npm view tns-ios versions --json` returns an array of versions, not as we expected an object. You can view the pull request opened here: [https://github.com/NativeScript/nativescript-cli/pull/2625](https://github.com/NativeScript/nativescript-cli/pull/2625). Thanks a bunch for your effort! Let me know if this fix sounds reasonable to you.

@dtopuzov The init command only creates a package.json definition just like `npm init` does. The reason why the `--force` flag was working is that it didn't search through the versions from the NPM but directly uses the latest version available. @rosen-vladimirov can you confirm this is the expected behavior, and not a full app created from a template?

Thanks guys!

**Comment by mnaughto** [comment]
@yyosifov #2625 is essentially what I did to get it to run - I didn't bother changing the signature of the `$npm.view()` function, but that change seems reasonable.
