### ISSUE TITLE
NativeScript CLI on OSX appends data into .bash_profile and corrupts core unix apps.... open

### ISSUE THREAD

**Issue by diverted247** [NativeScript/nativescript-cli#260]
After installing NativeScript CLI, the 'open' command stopped functioning and returned "Trace/BPT trap: 5" with many calls. I traced this back to functions injected into .bash_profile that were linked to NativeScript.

Far from ideal.

**Comment by teobugslayer** [comment]
Hello @diverted247,

This is a know issue which we could not fix for the upcoming release next week. The work around is to open another terminal console or to manually fix the COMP_WORDBREAKS environment variable.

That said, if you can fix this issue, feel free to send us a pull request against https://github.com/Icenium/node-tabtab .

**Comment by diverted247** [comment]
This just went from bad to pathetic.
So Telerik is "ok" shipping something "known" to corrupt the terminal environment on OSX/Linux.

Uninstall...

**Comment by rosen-vladimirov** [comment]
Hi @diverted247 
We've applied a fix in our node-tabtab repository that should fix the problem. Please note that the code in tabtab is forked from npm itself. As you can see here: https://github.com/npm/npm/blob/master/lib/utils/completion.sh#L10 
COMP_WORDBREAKS variable is reset by npm itself. Our code just adds the change to .bashrc and .bash_profile in order to allow completion of commands and options. On some systems this is causing errors as COMP_WORDBREAKS variable receives incorrect value. 
Anyway we've removed the code that  exports the variable from .bashrc and .bash_profile, so you can try installing latest nativescript-cli version and see if you still receive "Trace/BPT trap: 5" errors.
Hope this helps.

**Comment by spacepluk** [comment]
While I'm not as annoyed as @diverted247, I agree that it's not ok to mess with people's dotfiles without at least giving a warning.  I'd prefer enabling autocompletion as a manual step of the installation. Just my 2cents.

Now back to test this, it looks awesome :P

**Comment by rosen-vladimirov** [comment]
Hi @spacepluk, 
Thank you for the valuable feedback. As I've said - we've removed the part of the code, which was causing this error. However we find your idea to enable auto completion only in case the user accepts it, very interesting and we'll definitely consider improvements in this area.

**Comment by rosen-vladimirov** [comment]
Hi @spacepluk, @diverted247,
I just want to update you on this case. Base on your feedback we've decided to ask the user for confirmation before writing to .bash_profile and .bashrc files. This behavior is already part of the master branch, so you can give it a try immediately.
I'm closing this thread now, the related one for the feature implementation is [here](https://github.com/NativeScript/nativescript-cli/issues/350)
