### ISSUE TITLE
Support installation from a single NPM repository

### ISSUE THREAD

**Issue by manojtc** [NativeScript/nativescript-cli#2601]
In order to setup NativeScript at work, I downloaded the dependencies that were referenced from github and published them to the private npm repository. And then, I cloned the source code from github and modified the package.json file to pick dependencies from the private npm repository (we use Sonatype Nexus).

I had to do the same thing for a couple of dependency's dependencies too. I got it to work, but I probably would have to repeat the process again when we upgrade.

If NativeScript would pick up dependencies from a single NPM repository and avoid directly downloading from github, that would make it a lot easier to adopt in corporate environments. Would it be possible to ensure that the dependencies are published packages on the NPM registry ?

**Comment by manojtc** [comment]
I would like to contribute but I don't know why exactly NativeScript uses dependencies from GitHub even if there are published packages on NPM and whether there would be problems if those dependencies are replaced with NPM versions.

**Comment by rosen-vladimirov** [comment]
Hey @manojtc ,
I'm not sure why you are unable to install CLI from npm directly. This is a potential problem for creating/building your projects, as each NativeScript application relies on some npm packages. Anyway regarding your question - we use some packages from github as we have forked them and applied fixes. These fixes are not available in the original version of the packages (due to different reasons). 
In case you want to prepare a package that everyone in your company can install, I would suggest you to try the following approach:
1. Install nativescript cli on your own machine in any folder (where you are not behind a proxy): `npm i  nativescript`. 
2. Find the installed package of CLI - it should be in your node_modules/nativescript directory.
3. Edit the CLI's package.json and add `bundledDependencies` section - add all CLI's dependencies in it. The bundledDependencies are the dependencies, which will be included in your final package that we'll create later. More information about bundled dependencies is available [here](https://docs.npmjs.com/files/package.json#bundleddependencies)
4. Execute `npm pack` - this will produce a new package of NativeScript CLI, which will include all dependencies added in the bundledDependencies section. 

You can share this package with your teammates and all of you should be able to install it via `npm i -g <the produced tgz file>`.

Hope this helps. I'm closing this thread as currently we cannot easily remove the dependencies installed from github (also we do not analyze the whole dependency tree - a dependency of dependency of dependency may still use github url). Feel free to contact us in case you still have any issues or concerns.
