### ISSUE TITLE
`tns run android --clean` does not work as described in help

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2636]
According to CLI command line help:
```
* --clean - If set, forces rebuilding the native application.
```

Actual behavior with master branch:
I can't see something different (such as rebuild of the app)

Steps to reproduce:
```
tns run android (and start make changes on the project)
Ctrl+C
tns run android --clean => No rebuild is performed.
```

We should take same action to make help and behavior consistent - either fix the command or fix help.

**Comment by NathanaelA** [comment]
Agreed, I just came here to report this -- I ran into this when I did:
1. tns create project
2. tns run android
3. Make some changes
4. tns run android --clean  

I had expected to see **--clean** do a full reset, but it did the normal live sync.   
We really need **--clean** to do a full rebuild; so that I no longer have to do a:
```
tns run android
tns build android
tns run android 

```
To get a "clean" build...
