### ISSUE TITLE
What is the debugging story?

### ISSUE THREAD

**Issue by svdoever** [NativeScript/nativescript-cli#279]
Given the open source NativeScript project, what are the debugging options? I understand that it is possible to debug from AppBuilder, a payed option AND a Windows application. What are the free options and OSX/Linux options for debugging?

**Comment by rosen-vladimirov** [comment]
Hi @svdoever 
I suggest you to check "debug" command in nativescript-cli. Just try ```$ tns debug -h``` and you'll get the required information. Please note that we are working on improvements in this area, so if you find some issues, feel free to share them or even fix them and send us a pull request :) 
Here's one example how you can use debug command: start your app on attached device (you can use ```$ tns deploy android``` in order to deploy it) and after that execute ```$ tns debug android --start```

**Comment by LOUIStheXIVTH** [comment]
Is it possible to debug while your app is running on the emulator?

**Comment by Fatme** [comment]
Yes, it is possible only for android platform. We are working to add support for ios too.

**Comment by teobugslayer** [comment]
iOS support landed in master and will be available in our next public release.
