### ISSUE TITLE
tns debug android fails with 3.0.1

### ISSUE THREAD

**Issue by hshristov** [NativeScript/nativescript-cli#2877]
When executing `tns debug android` with runtime 3.0.1 the app gets started on emulator but terminal shows the following error:

```
# NativeScript Debugger started #
Multiple errors were thrown:
Multiple errors were thrown:
The application org.nativescript.tests does not appear to be running on emulator-5554 or is not built with debugging enabled.
# debug android
```

**Comment by hshristov** [comment]
This happens when I delete `tmp` folder:
```
adb shell
su
cd data/local/
rm -rf tmp/
```

**Comment by hshristov** [comment]
Fixed after emulator is deleted and created a new one.

**Comment by rosen-vladimirov** [comment]
The problem is that `/data/local/tmp` directory is deleted and CLI tries to create it during debugging process. However, on some Android emulators, the shell user (that CLI uses) does not have rights to create the `/data/loca/tmp` dir and that's why the debugging fails.
Anyway, it is not a good practice to delete `/data/loca/tmp`. Instead, you should delete `/data/local/tmp/<app-id>` dir and `/data/local/tmp/<app-id>-debug* files. 
The `/data/local/tmp` dir is symlinked and used by the Android OS itself. 

As a workaround you can restart the emulator and this will create the `/data/local/tmp` dir with correct privileges.
