### ISSUE TITLE
Application restarts on changes in .xml file when debugging

### ISSUE THREAD

**Issue by vtrifonov** [NativeScript/nativescript-cli#2992]
When I start
`tns debug ios` 
or 
`tns debug android`
with a brand new application created with the following command:
`tns create HelloWorld --template nativescript-template-tutorial`
and make changes in the .xml file the application restarts in the emulator, which I thing is not expected since I'm not changing the javascript files. 
I'm using the currently latest version 3.1.2.

**Comment by rosen-vladimirov** [comment]
Hey @vtrifonov ,
At the moment all changes during debug are causing restart of application. This is by design, but we've already discussed changing this behavior. As far as I understand, your expectation is to have the same experience during `debug` and `run` .
Thank you for logging this issue. It will be great in case we receive more feedback from the community on this case. This will help us to decide which should be the default behavior of the `tns debug` command when `.xml` file is changed.

**Comment by vtrifonov** [comment]
Yes, that's what I expect. The behaviour to be the same as when using `run`. As far as I remember in the older versions this was the behaviour? And it is faster, or at least looks like it's faster :)

**Comment by DimitarTachev** [comment]
The new behavior will be available in `Chrome` and `Inspector`with both `Devices` and `Simulators/Emulators`.

The behavior of `--justlaunch`, `--watch`, `--no-watch` and `--start(attach)` options will not be affected.

It should support the following use cases:
- [ ] attach, livesync, deatach, livesync, attach.
- [ ] livesync, attach, livesync, detach, livesync.
- [ ] (should) "To start debugging, open the following URL in Chrome" message should be shown only when no debugging client is connected.
- [ ] the livesync behavior should be as follows:

| livesync  | css/html/xml/css | js | notes |
| ------------- | ------------- | ------------- | ------------- |
| debug  | refresh  | restart | |
| debug --hmr  | refresh |refresh  | |
| debug --debug-brk  | restart | restart  | |
| debug --hmr --debug-brk  | restart | restart  |  impossible hmr warning |
