### ISSUE TITLE
Stopping the app causes the terminal and google chrome to stop working until the computer is restarted

### ISSUE THREAD

**Issue by chrillewoodz** [NativeScript/nativescript-cli#3001]
### Did you verify this is a real problem by searching [Stack Overflow]
Yes this is a real problem.

### Tell us about the problem
As soon as I run `tns run ios` and then stop it, I get 

```
update_terminalapp_cwd:4: fork failed: resource temporarily unavailable                                             
zsh: fork failed: resource temporarily unavailable
```

And I can't use the terminal any more until I restart my computer. That error seems to come from too many processes running, so there's obviously something related with running the app that causes the terminal to go bananas. 

The same goes for Chrome, that completely stops working as well. If I try to open a new tab I get their sad face and nothing happens. 

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.1.2
- Cross-platform modules: 3.1.0
- Runtime(s): 3.1.0
- Plugin(s): I'm not sure what this means exactly but here's what I'm using:

```
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "lodash": "^4.17.4",
    "nativescript-angular": "~3.1.0",
    "nativescript-geolocation": "^3.0.0",
    "nativescript-google-maps-sdk": "^2.3.2",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "~3.1.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "nativescript-dev-sass": "^1.2.0",
    "nativescript-dev-typescript": "~0.5.0",
    "typescript": "~2.2.1"
  }
```

### Please tell us how to recreate the issue in as much detail as possible.
Get a brand new MacBook Pro with a 500GB SSD and the best of the best hardware and then try to run a simple hello world app on IOS using NativeScript and the zsh terminal. And you should see this error.

**Comment by rosen-vladimirov** [comment]
Hey @chrillewoodz ,
The error `zsh: fork failed: resource temporarily unavailable` definitely indicates some problems with max number of processes and resources available on the machine. We've seen this error on some machines, where the default limits for max opened files and running processes are very low. During LiveSync CLI starts file system watcher, which results in increasing the number of opened files and file system watchers on the machine. I believe the problem on your side is caused by the second on - number of running file system watchers. You can check the current limit by executing:
```
cat /proc/sys/fs/inotify/max_user_watches
```
On some machines the value is 8192 which is not sufficient in many cases.

More information how to increase the number is available [here](https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers)

Can you check the current value of `max_user_watches`, try increasing it and see if the issue is still reproducible?

**Comment by chrillewoodz** [comment]
Thanks for the reply. I try to run `cat /proc/sys/fs/inotify/max_user_watches` but it says `no such file or directory`.

**Comment by rosen-vladimirov** [comment]
Hey @chrillewoodz ,
Please excuse me, I've referred the manual for Linux. On macOS you can use the `sysctl` directly in order to get and set the values of max number of processes, opened file system entries, etc. 
You can try:
```
$ sysctl kern.maxproc
$ sudo syctl kern.maxproc=<new higher value>
$ sysctl kern.maxfilesperproc
$ sudo syctl kern.maxfilesperproc=<new higher value>
$ sysctl kern.maxfiles
$ sudo syctl kern.maxfiles=<new higher value>
```
As far as I know, sysctl will set the values only for your current session. In case you reboot your machine, the values will be reset to their defaults. More information how to persist the values set with sysctl after reboot of the machine is available [here](https://blogs.progarya.dk/blog/how-to-persist-ulimit-settings-in-osx/).

Can you try modifying the specified keys and see if this will resolve the issue on your side?

**Comment by chrillewoodz** [comment]
Ok I will do and get back to you. I just tried now to run `sysctl kern.maxproc` and I get a mere `1064`. Which according to your initial figure of `8192` is way below what it should be. Hopefully I can manage to increase it.

**Comment by rosen-vladimirov** [comment]
Ok, thanks for your cooperation. Just for clarification - the 8192 value is the minimum of `kern.maxfilesperproc` - that's the number of the files which can be opened from single process.
The `kern.maxproc` value is used to define the maximum number of processes that can be run on your machine. You can get the current number of running processes by executing:
```
ps -ef | wc -l
```
Maybe you have some other programs running and once CLI is started you exceed the limit of 1064?

**Comment by chrillewoodz** [comment]
I followed the link to persist the changes but I still get `1064` as the `maxproc`. I also tried running your commands for temporarily setting a higher number but I get `syctl: command not found` because `syctl` should be `sysctl` but then I get `sysctl: kern.maxproc=15000: Invalid argument` when running `sudo sysctl kern.maxproc=15000`.

**Comment by chrillewoodz** [comment]
Ok so after running all of the above commands for `maxfiles`, `maxproc` and `maxfilesperproc` I still encounter this issue. I set all of them to double the default amount.

**Comment by rosen-vladimirov** [comment]
Hey @chrillewoodz ,
Please excuse me for the late reply. Based on your answers I believe doubling the `kern.maxproc` value is working in your current session, but you still have problem to set it permanently. Am I right ?

**Comment by chrillewoodz** [comment]
@rosen-vladimirov I can set it yes, but it seems to have no effect on the issues I'm experiencing. Since doubling every value did nothing, I am not sure how to proceed from here.

**Comment by danielmarkland** [comment]
I'm experiencing the same thing. Any more ideas?

**Comment by chrillewoodz** [comment]
@NickIliev I just tried nativescript again after giving up on it, tried it using the Angular CLI and it seems like the error is gone. If it comes back I'll let you know.
