### ISSUE TITLE
No console.log output Xcode 9 iOS 11

### ISSUE THREAD

**Issue by terreb** [NativeScript/nativescript-cli#3141]
### Did you verify this is a real problem by searching [Stack Overflow]
I took time to search, but haven't found anything mentioning this issue.

### Tell us about the problem
After upgrade to Xcode 9 and using iOS 11 simulator I'm not seeing console.log output after "tns run ios" any more.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.2.1
- Cross-platform modules: tns-core-modules 3.2.0
- Runtime(s): tns-ios 3.2.0

Xcode 9.0 (9A235)
Simulator iPhone 6 iOS 11.0 (15A372)

**Comment by KristianDD** [comment]
Thank you for the report. I can confirm that this is indeed an issue and we are currently working on a resolution.

As a temporary workaround open the Console app on Mac and from the Devices list select the connected device. Now in the right pane you can see all messages coming from the selected device. In the Search field type `proc:YourAppName` to see only the log coming from yours app process.

**Comment by terreb** [comment]
@KristianDD, ok, thank you for the tip!

**Comment by justindujardin** [comment]
Another workaround is to use the `tns debug ios` and the console output will be shown in the inspector.

**Comment by terreb** [comment]
@justindujardin, yeah, I know that, but "tns debug" became so slow and hangs too often after update to Xcode 9 / iOS 11 that I would use "run" instead if I could.

**Comment by briosheje** [comment]
@terreb If you use the watch you shouldn't have huge issues with `tns debug`. I've had to use it aswell since Xcode 9, it's just a bit slow when you run the instance, but as long as you use what you should be able to work with it, it shouldn't take a significant time to load everything (about 5 to 10 seconds in my case).

**Comment by justindujardin** [comment]
@terreb Agreed that the inspector is not a great workaround. I ended up downgrading because I didn't need XCode 9, it was installed as part of the automatic update process.

The console being gone really hindered my development, and as you point out the inspector makes for really slow iterations, so it made sense to downgrade XCode until a fix is published. Now my console is back, and I only have to worry about the inspector slowly eating itself when I have to debug something. 😅 

If it makes sense for your project, and you have a valid developer account with Apple, you can downgrade like this:
- [Download the 8.x version of your choosing](https://developer.apple.com/downloads/index.action) 
- Drag your current XCode app into the trash.
- Extract the downloaded XCode and drag into `Applications`

**Comment by NathanaelA** [comment]
Please note; I document how to fix logging on my blog for both the missing ios logging (other reported bugs) and this new issue with no logging for iOS 11 emulators on my blog:  http://fluentreports.com/blog/?p=545  -- It is a very simple command line and you will again have logging from all your iOS 11 emulators.  😀

**Comment by terreb** [comment]
@justindujardin, I can see logs for simulators with iOS <11, so no need to downgrade Xcode for that:)

@NathanaelA, wow, thank you a lot! This is an easy and really cool workaround that works perfectly fine for me.

**Comment by fuyacho-takatsuji** [comment]
@NathanaelA :: it does not work :: ERROR Could not start service com.apple.syslog_relay

**Comment by NathanaelA** [comment]
@fuyacho-takatsuji - You need to use the version of both usbmux and idevicesyslog on **head**.   The stock versions in brew doesn't support the newer ios 11.

**Comment by dtopuzov** [comment]
@fuyacho-takatsuji @terreb @justindujardin @briosheje 
The issue is fixed in `nativescript@next` and will be officially released soon with 3.3.0.
