### ISSUE TITLE
Run tns doctor waiting too long

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#3215]
_From @tolerious on November 11, 2017 12:21_

After I  run `tns doctor`  I got this,
<img width="1420" alt="2017-11-11 8 19 10" src="https://user-images.githubusercontent.com/2922120/32689345-c5a5529c-c71d-11e7-84a4-1f47cd17dc03.png">
and I have waited for a long time.

_Copied from original issue: NativeScript/NativeScript#5062_

**Comment by rosen-vladimirov** [comment]
Hey @tolerious,
Does the `tns doctor` command finish at some point? Its execution is slow, because it verifies different components on your machine and also tries to prepare a sample project with Cocoapods. The last step installs some packages from npm and tries the `pod install` command in the newly created Xcode workspace. This operation will trigger Cocoapods to update their repository (in some cases), which may additionally slow down the process. 
We are aware of this, but the most important work of `tns doctor` is to verify your machine can create and build NativeScript applications. We'll try to improve the speed of the operations in the future, but meanwhile can you confirm the command succeeds at the end?

**Comment by tolerious** [comment]
@rosen-vladimirov 

now I got this

![2017-11-14 10 13 53](https://user-images.githubusercontent.com/2922120/32759545-edd2a37e-c924-11e7-8497-8dd0cc7fa33a.png)


does that mean I have configured the nativescript correctly?

**Comment by rosen-vladimirov** [comment]
Hey @tolerious ,
Yes, the message at the end says "No issues were detected", so you should be able to use NativeScript to create, build, run project for both iOS and Android.
Can we mark this issue as resolved?

**Comment by tolerious** [comment]
@rosen-vladimirov  sure, please close this issue, thank you very much.  ^.^
