### ISSUE TITLE
Support brew version of Cocoapods

### ISSUE THREAD

**Issue by jaxondu** [NativeScript/nativescript-cli#3276]
I'm using the brew version of Cocoapods on macOS instead of Ruby gem version. The brew version also has xcodeproj binary installed in the path. tns CLI however is expecting the gem version of xcodeproj when you run "tns doctor" and "tns run ios". Please support brew version of cocoapods by checking xcodeproj in the path instead of in the gem list.

**Comment by rosen-vladimirov** [comment]
Hey @jaxondu ,
Thank you for the information. I confirm there's a problem with current detection. The check for xcodeproj is `gem which xcodeproj`, instead of just spawning `xcodeproj --version`.
In order to fix this, the following changes should be applied:
1. Fix the call from `gem which xcodeproj` to `xcodeproj --version` [here](https://github.com/telerik/mobile-cli-lib/blob/master/sys-info-base.ts#L70-L80). We do not need the exact location of the gem, we need it to be installed, so it is a good idea to rename the method and the related properties.
2. Fix the code in [ios-project-service.ts](https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/ios-project-service.ts#L1048-L1053) to use the methods from `sysInfo` when checking if `pod install` can be called, something like:
```TypeScript
const cocoapodVersion = await this.$sysInfo.getCocoapodVersion();
const xcodeProjVersion = await this.$sysInfo.getXCodeProjGemVersion();

if (!(cocoapodVersion || xcodeProjVersion)) {
	this.$errors.failWithoutHelp("CocoaPods or ruby gem 'xcodeproj' is not installed. Run `sudo gem install cocoapods` and try again.");
}
```

It should be pretty straightforward, so we'll be glad to review PRs in case you want to give it a try.
