### ISSUE TITLE
[Feature Request] Playground-like, live-reloading app previews from QR code.

### ISSUE THREAD

**Issue by alshdavid** [NativeScript/nativescript-cli#3287]
First of all, I love what you're doing with NativeScript. Glad that we are beginning to have an alternative to React Native, and it's compatible with more than just Angular.

I tried out NativeScript on the playground and loved how it worked. Just like React Native - iOS, Android - I just have to scan a QR code and I am away with live reloading. 

So I installed the sidekick. I quickly realised that I needed to install the Android SDK, and attach my device before I could test my app with live reload. There was no QR based development, like in the playground, when you're using the real dev tool.

Does the NativeScript team have any plans to include QR code based development previews within the CLI or sidekick?
If not, what are your opinions on including it?

**Comment by teobugslayer** [comment]
Hello @alshdavid,

Our current thinking is that such app is not feasible for actual app development, as opposed to the carefully curated experience in the Playground. Why is that?

The Playground is for learning NativeScript core concepts and quickly trying out code. That's why its Companion app needs to carry only the core framework bits and selected few plugins to ensure that goal.

However, when developing a feature rich app, the programmers need to use different plugins - some publicly available, some developed by themselves. We cannot publish in the public app stores a companion app which includes all (or even most) of the plugins - the cost to support it would be enormous, plus it won't work for everyone anyway. Such app would weight more than 100 MB(!) and the team would need to re-certify it practically every week to keep up to date.

-------

However, Progress is developing a premium tool which could help you -[NativeScript Sidekick](https://www.nativescript.org/nativescript-sidekick).  The tool is free, and the associated cloud services have free tier. You can use it develop NativeScript apps comfortably without the need to install and maintain Android SDK, Xcode, and you can even develop iOS apps without a mac.

**Comment by rosen-vladimirov** [comment]
This is already implemented with `tns preview` command.
