### ISSUE TITLE
Application name is changed when rename the project folder

### ISSUE THREAD

**Issue by Natalia-Hristova** [NativeScript/nativescript-cli#3447]
### Tell us about the problem
Renaming project folder changes the application name

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: `3.4.2 `and `next`

### Please tell us how to recreate the issue in as much detail as possible.
1. `tne create SomeApp`
2. Rename the folder e.g. SomeApp to NewApp
3. `tns run android`

in the `package.json` the `id:` is the **old folder name** 
in `../platforms/android/app/src/main/res/values/strings.xml` 
` <string name="app_name">NewApp</string>`

**Comment by rosen-vladimirov** [comment]
Hey @Natalia-Hristova ,
This is by design since Day 0 of NativeScript. In the package.json we persist the application identifier, while the Project Name is generated from the project directory. The idea comes from the `tns create <project name> ` command - it creates a directory with the specified name and this name is used for application name later. The application identifier can be specified with `--appId <applciation identifier`. 
When the directory is renamed, during project preparation CLI uses the new name to set the application name. In case you do not want this behavior, you can hardcode your app name in the `<project dir>/app/App_Resources/Android/AndroidManifest.xml` and `<project dir>/app/App_Resources/iOS/Info.plist`

**Comment by hettiger** [comment]
@rosen-vladimirov Can you be a bit more specific on how one could hardcode the app names?

(e.g. on iOS I've already specified the CFBundleName which is not being used. In fact I'm running into issues with the .entitlements file. I think one is not really free when it comes to folder naming.)

**Comment by mhlulani** [comment]
in your `app-name/App_Resources/Android/src/main/AndroidManifest.xml` (for android)
```xml
	<application
		android:networkSecurityConfig="@xml/network_security_config"
		android:name="com.tns.NativeScriptApplication"
		android:allowBackup="true"
		android:icon="@drawable/icon"
		android:label="<HARD_CODED_APP_NAME>"
		android:theme="@style/AppTheme"
		android:launchMode="singleTask">
...
```
