### ISSUE TITLE
Ability to tns run app on multiple iOS emulators

### ISSUE THREAD

**Issue by ickata** [NativeScript/nativescript-cli#3494]
Hello,

While having multiple Android emulators running at the same time and {N} live syncing to all of them, this does not work on iOS emulators. I am able to run multiple emulators at the same time, however `tns run ios` syncs to only one of them.

### Please provide the following version numbers that your issue occurs with:

- CLI: 3.4.3

### Please tell us how to recreate the issue in as much detail as possible.

Launch iOS emulator and choose different device from Hardware –> Device. This will open another instance of emulator. Then `tns run ios`.

**Comment by rosen-vladimirov** [comment]
Hey @ickata ,
The issue is already logged [here](https://github.com/NativeScript/nativescript-cli/issues/3321). You can follow its progress there. In fact, you can try our `rc` version (`npm install -g nativescript@rc` ) where we've included partial support for multiple simulators - CLI will detect them and try to use them. The livesync may not work in some cases, but still, you should be able to work with the simulators.

**Comment by ickata** [comment]
Thanks, Rosene. I did search before posting this issue, but did not find the one you referenced. Sorry for the duplication.
