### ISSUE TITLE
iOS build breaks with multiple plugins with podfiles

### ISSUE THREAD

**Issue by lini** [NativeScript/nativescript-cli#3604]
### Tell us about the problem
If an app has multiple plugins and they have podfiles with a platform defined like 

    platform :ios, '9.0'

the combined podfile will have multiple platform lines and the build will fail. 

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
nativescript@4.0.1
nativescript-imagepicker@6.0.1
kinvey-nativescript-sdk@3.10.4

### Please tell us how to recreate the issue in as much detail as possible.
Create an app, add nativescript-imagepicker@6.0.1, add kinvey-nativescript-sdk@3.10.4. Try to build app for iOS.

Reported in https://github.com/NativeScript/nativescript-imagepicker/issues/186

**Comment by RobertGardner** [comment]
Is there any resolution to this? It seems that the CLI, when merging plugin podfiles, should check for `platform :ios` conflicts and fix them, probably by keeping only the one with the highest version number.

(It looks like this would happen in `cocoapods-service:applyPluginPodfileToProject()`.)

**Comment by NickIliev** [comment]
+1 from `kinvey-nativescript-sdk` plugin. [https://github.com/Kinvey/nativescript-sdk/blob/master/platforms/ios/Podfile#L1](https://github.com/Kinvey/nativescript-sdk/blob/master/platforms/ios/Podfile#L1)

**Comment by burkongla** [comment]
+1 nativescript-stripe

**Comment by jjstrat3** [comment]
Anyone here have a workaround for this?  This seems like a major issue and it's currently blocking us from using another plugin.

**Comment by burkongla** [comment]
One work around if you are building locally: 
You can first build the project, remove the extra platform line from the built Info.plist inside platforms/ios and build again without removing the platforms folder of course. 

However, we are using nativescript sidekick, and I do not know what to do in that case, so other suggestions would be nice.

**Comment by RobertGardner** [comment]
I have found with nativescript-firebase if you completely remove the "ml_kit" entry from `firebase.nativescript.json` then it does not emit the `platform :ios` line. That was enough to solve the problem for me.

Since NativeScript doesn't seem to be doing anything about this, maybe plugin authors should just remove that line from their Podfiles, document which iOS version the plugin requires, and rely on developers to honor it. I'd be happy to do that for nativescript-stripe until NativeScript addresses this issue if it will help anyone.

**Comment by GeorgeKyriakou** [comment]
@RobertGardner what if I am using the `ml_kit` library, and need to have it in the .json file?
Is someone looking at this???

**Comment by RobertGardner** [comment]
It looks like a Bug label was added on May 21, but has there been activity since then? What is NativeScript's official response to this?

A workaround that can be done at install time (as opposed to build time as suggested by @burkongla ) would be to find `platforms/ios/Podfile` for the offending plugin(s) and delete the `platform  ios` line there. This would only need to be done when you (re)install the plugins (such as after `npm i`) instead of after every build.

I don't use NativeScript Sidekick, so I don't know if it tries to reinstall the plugins on every build (though that could be time consuming, so I doubt it).

**Comment by NeriCodec** [comment]
+ 1 nativescript-mediafilepicker

**Comment by endarova** [comment]
- [ ] Verify if you have plugins with podfiles with specified platform version in them (platform :ios, '9.0'), when building only the highest platform version specified will be used.
- [ ] Verify if you have podfile in AppResources folder with specified platform version in it  (platform :ios, '9.0'), when building only that version will be respected
- [ ]  Verify when  plugins with podfiles with specified platform in them and podfile in AppResources folder without specified platform in it, the highest platform version from plugin podfiles will be used.
- [ ] Verify if you have plugins with podfiles with specified platform without version  (platform :ios)  the highest available version will be used
- [ ] Verify changes in platform versions in podfiles are updated on livesync
- [ ] Verify when add/delete podfiles  platform versions are updated

**Comment by endarova** [comment]
Fixed in tns@5.2.1
Have in mind that if your pod file is already corrupted with multiple declarations of platform:ios you will have to delete the platforms folder of your project in order to apply the new tns behavior for podfiles.

**Comment by NathanWalker** [comment]
@endarova this is incredibly exciting news! Worthy of a blog post about just this alone ;) @rosen-vladimirov 🤗

**Comment by vforv** [comment]
Same problem with nativescript feedback plugin
https://github.com/EddyVerbruggen/nativescript-feedback/issues/49

**Comment by rosen-vladimirov** [comment]
Hey @vforv , 
Can you please try with latest CLI (5.2.2) - just execute `npm install -g nativescript@latest` to get it on your machine. After that, delete your platforms directory and try `tns run ios` again.

**Comment by vforv** [comment]
Works, thanks! How can I make change localy? When I try tns update it still setting old version of cli?

**Comment by rosen-vladimirov** [comment]
@vforv in your local project, you shouldn't have reference to nativescript package - this us the CLI, so it is expected to have other only globally
