### ISSUE TITLE
Gradle timeout lock on file when running build android 

### ISSUE THREAD

**Issue by moda20** [NativeScript/nativescript-cli#3606]
### Tell us about the problem

I cloned the sample-groceries  repository and tried to build it for android. 
I run `tns build android` for the first time and it shows this error : 

```
FAILURE: Build failed with an exception.

* What went wrong:
Timeout waiting to lock Build Output Cleanup Cache (/Volumes/NO NAME/sample-Groceries/platforms/android/.gradle/buildOutputCleanup). It is currently in use by another Gradle instance.
Owner PID: unknown
Our PID: 1128
Owner Operation: unknown
Our operation: 
Lock file: /Volumes/NO NAME/sample-Groceries/platforms/android/.gradle/buildOutputCleanup/cache.properties.lock
```
Note  : the `NO NAME`volume is a fat32 volume. and I am running OSX 10.13

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI:  4.0.1
- Cross-platform modules:  4.0.0
- Runtime(s):
```
"tns-ios": {
      "version": "4.0.1"
    },
    "tns-android": {
      "version": "4.0.0"
    }
``

### Please tell us how to recreate the issue in as much detail as possible.

- Clone the sample-groceries 
- run `tns build android`

**Comment by NickIliev** [comment]
@moda20  the issue seems related to your local environmental the sample-Groceries is building as expected on my side and our nightly tests. Make sure Gradle is not used by several users simultaneously (log out any users that might be using Gradle instance). The issue seems more related to tns-android (Android runtime) so if the problem persists please post an issue in [this repository](https://github.com/NativeScript/android-runtime/issues).
