### ISSUE TITLE
 livesync slow

### ISSUE THREAD

**Issue by HosseinAlipour** [NativeScript/nativescript-cli#3674]
I watched this old [video](https://egghead.io/lessons/angular-2-edit-with-live-reloading-using-nativescript-livesync) explaining how to livesync ( now `run` ), but my project takes 15-20-30 seconds for every file changes even on css files. i run on angular and the application startup takes roughly about 10 seconds, how do Nathan Walker in the videos livesync so fast?
I'm soo exhausted ;( any help will be appreciated.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI:  4.1.0
- Cross-platform modules: 4.1.0
- Runtime(s):  4.0.1
- Plugin(s): which plugin?!

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Consider using the [playground](https://play.nativescript.org) to provide the code you have issues with.

**Comment by abney317** [comment]
Same issue here with iOS. Every time I save it spends 20 seconds building the project and loading it up again. Extremely basic test project too. Was just the blank template pretty much.

**Comment by kevincam3** [comment]
Same here, I thought it was just me but yeah this this is frustratingly slow

**Comment by NL33** [comment]
Is there any update on this issue? I updated my cli (December 2018) to the latest version, and now livesync is extremely slow (this afternoon the livesync has taken about 2 mins per any small change).

**Comment by dtopuzov** [comment]
Hi all,

We shipped beta version of HMR which makes sync changes almost instant with 5.0 release and we will further improve it for 5.2 release scheduled for mid Feb.

Tracking issue for HMR progress:
https://github.com/NativeScript/NativeScript/issues/6398

Re slow strat of angular apps:
- It can be 10sec on physical devices when app is not optimised at all
- It will be much faster if you use emulators and simulators when you develop you app (since they use the full power of your desktop CPU)
- App starup time can be improved when you use --bundle (for production bulds you can apply further optimisation such as ahead of time compilation and snapshots)

Startup time optimizations resources:
https://docs.nativescript.org/performance-optimizations/startup-times

If you still encounter slow livesync with nativescript@5.1 please log separate issue and provide as much details as possible (sometimes extra restarts might be caused by issues in plugins, so please post package.json of your projects).
