### ISSUE TITLE
Can't resolve scss files

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#3699]
_From @waszqba on June 21, 2018 10:39_

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
yes

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: 4.0.0
- Runtime(s): 4.1.3
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

I have a problem with building and properly running the whole application. It was all fine on my device, it ran like a charm every time, but today there's some kind of a problem with imports. when I start `tns debug android` it builds the app and tries to launch it, but as soon as the splash screen passes, I get this:
```
JS: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
JS: ns-renderer: Could not resolve /data/data/eu.neoteric.skillhunt/files/app/~nativescript-theme-core/scss/light. Looked for: /data/data/eu.neoteric.skillhunt/files/app/~nativescript-theme-core/scss/light.
JS: 
JS: Error: Could not resolve /data/data/eu.neoteric.skillhunt/files/app/~nativescript-theme-core/scss/light. Looked for: /data/data/eu.neoteric.skillhunt/files/app/~nativescript-theme-core/scss/light.
JS:     at FileSystemResourceLoader.resolve (file:///data/data/eu.neoteric.skillhunt/files/app/tns_modules/nativescript-angular/resource-loader.js:33:19) [<root>]
JS:     at FileSystemResourceLoader.get (file:///data/data/eu.neoteric.skillhunt/files/app/tns_modules/nativescript-angular/resource-loader.js:19:33) [<root>]
JS:     at DirectiveNormalizer._fetch (file:///data/data/eu.neoteric.skillhunt/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:3186:43) [<root>]
JS:     at file:///data/data/eu.neoteric.skillhunt/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:3382:41 [<root>]
JS:     at Array.map (<anony...
```
And this is after modifying `app-variables` imports to be `_app-variables.scss` everywhere, because that's what it couldn't find at first, but I can't modify bundle files.
Any help with that?

_Copied from original issue: NativeScript/NativeScript#5981_

**Comment by rosen-vladimirov** [comment]
Hey @waszqba ,
I'm not sure what exactly is causing the issue. Can you try cleaning your project and building it again? In order to do this, please follow the steps below:
1. Delete your local `<project dir>/platforms` directory.
2. Uninstall the application from device.
3. Use `$ANDROID_HOME/platform-tools/adb shell` to enter a terminal session on the device.
4. In the terminal session execute `cd /data/local/tmp`
5. There you will find a directory called with your application identifier, for example `org.nativescript.myapp` - just delete it (`rm -rf org.nativescript.myapp`).
6. Exit the terminal session (write `exit`)
7. Try running your debug command again: `$ tns debug android`

Can you give it a try and inform us if it works for you?

**Comment by waszqba** [comment]
Hi @rosen-vladimirov, Sorry for late reply since I've lost track of some my issues recently.
I've tried to follow steps described by you couple of times but the error persists, so though luck, we need to look further.
on refresh I only got difference in the file not being found, which is `/data/data/id.of.app/files/app/app_variables`

**Comment by waszqba** [comment]
We managed to run the app somehow by switching `app.android.scss`'s `@import` statement from `app_variables` to `./app_variables`. Not sure what happened, because the project was freshly downloaded from repo couple days ago and worked like charm until now (we've added new devs to the team)

**Comment by rosen-vladimirov** [comment]
Hey @waszqba ,
Can we close this issue as it seems resolved?
