### ISSUE TITLE
Still a problem: Problem building nativescript-google-maps-sdk on Android #1081

### ISSUE THREAD

**Issue by vtrifonov** [NativeScript/nativescript-cli#3751]
_From @sserdyuk on July 3, 2018 20:35_

This is an attempt to bring attention to the fact that #1081 still has people reporting issues, but the issue is closed, so it must be flying under your radar. 

Please see the [following comments](https://github.com/NativeScript/android-runtime/issues/1081#issuecomment-397373338).

_Copied from original issue: NativeScript/android-runtime#1105_

**Comment by NathanaelA** [comment]
Yeah, this just bit me too; since it doesn't use the master application gradle file, the change their would do nothing.  Then I attempted to change the one on the platforms tempPlugin and it would get changed back under me.    

Very annoying; finally figured out that their must be a master copy somewhere it was copying and changed it and I'm now good. 

However, since this totally breaks building of several plugins (and thus the application you are trying to build) -- this really should be either released as 4.1.4 or if 4.2 is coming very soon make it into 4.2.    

If you need a PR, I can do one...

**Comment by rosen-vladimirov** [comment]
Hey @NathanaelA ,
This issue should be intermittent if I understand the exact problem correctly. If I'm not mistake, the problem is that sometimes jcenter gets unstable and Gradle fails to find exact resources. Am I right?
Anyway, 4.2.0 is just around the corner, but I welcome you to send a PR and I'll take care of including it in the release. Thanks for your help!

**Comment by NathanaelA** [comment]
@rosen-vladimirov - Unfortunatly, it is all the time with certain libraries.  JCenter doesn't have Google support libraries; and if the version you are requesting is a newer version then it has to download it. 

I don't really understand why; but when JCenter is first; it only checks JCenter then quits out with the error message about not being able to download support vXXX from JCenter     When JCenter is last; then it checks the other repos fine (and finds it in on Googles repo.   It is almost like their is something hard coded in Gradle to quit after JCenter (which I don't know for sure, but that is what it is acting like).  

I had to google the error message and I saw reports in RN, stock Android app; stack overflow, pretty much everywhere (very common issue apparently) and the solution was move JCenter below maven/google, and if you didn't have the maven { google... } line then to add it before JCenter.    

After I fixed it in my copy; I figured I'd drop a bug report and found that others had already ran into it and had reported it.  

I'll get you a PR shortly.  :grinning:

**Comment by NathanaelA** [comment]
@rosen-vladimirov #3769 is the PR.  :grinning:

**Comment by rosen-vladimirov** [comment]
@NathanaelA thanks for the explanation and the PR. It is merged in master and it will be included in the 4.2.0 release. 
@sserdyuk thanks for bringing the attention to this issue!

**Comment by odedBartov** [comment]
Any fix for this??? I am facing the same problem and nothing helped!
