### ISSUE TITLE
tns run output verbosity

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#3852]
_From @erkanarslan on August 29, 2018 15:6_

### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes

### Tell us about the problem
When I run `tns run` console output contains lots of unrelated logs. I cannot see what my app outputs. I always get logs about network connectivity and other things. They never stop. One of the devices is an android emulator, other one is a real iPhone 7.

Here is a screenshot.

<img width="855" alt="ekran resmi 2018-08-29 18 02 56" src="https://user-images.githubusercontent.com/11949947/44796652-15075600-abb6-11e8-8e83-7d02c092360f.png">

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.1
- Cross-platform modules: 4.1.1
- Runtime(s): 4.1.3 for Android and 4.1.1 for iOS
- Plugin(s): Unrelated

### Please tell us how to recreate the issue in as much detail as possible.
Run `tns run` on a project. You will see the output.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

_Copied from original issue: NativeScript/NativeScript#6227_

**Comment by Fatme** [comment]
Hi @erkanarslan,

Thank you for providing the screenshot.

As I can see from the screenshot you have angular application. 
Can you please check if the issue will reproduce with new projects? You will need to execute the followings:
1. `tns create myApp`
2. `cd myApp`
3. `tns run android`

If the issue is not reproduced with new projects, can you please provide us a list with your plugins?

It will be helpful and great appreciated if you can send us a project or code snippet demonstrating the issue.

**Comment by erkanarslan** [comment]
New project doesn't have this problem. I sent my project to your email address. You can see the list of plugins there. I use Nativescript since version 2.x. Maybe something is outdated in my project.

Thanks.

**Comment by erkanarslan** [comment]
It seems that this happens only on real iOS devices. Android and iOS emulators don't print those outputs.
