### ISSUE TITLE
Improve `ctrl + c` handling

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nativescript-cli#3993]
**Is your feature request related to a problem? Please describe.**
Currently, the CLI cannot be easily killed with `ctrl + c`. 

**Describe the solution you'd like**
Stop handling the SIGINT signals and let the nodejs do the job.

**Describe alternatives you've considered**
Extract a common helpers for managing the timeouts, intervals and child processes and keep the exit logic in a single place.

**Comment by rosen-vladimirov** [comment]
The issue should be fixed in latest `next` version of nativescript CLI. To get the full benefits of it, you can install CLI's next version by executing `npm i -g nativescript@next`.
The new approach of handling Ctrl + C is described in the related PR. The main concept is that now CLI does not handle SIGINT signal. Instead, it starts a new child process that will cleanup the resources once CLI's process dies. As the child process is detached and executes most of its work after CLI's dead, you can pass `--cleanupLogFile <path to file>` where the logs of the execution will be stored. The child process will execute the cleanup actions, write information to the specified file (in case the `cleanupLogFile` option is not passed, it will not create log) and after that it will exit.
