### ISSUE TITLE
Google play app signing

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#4040]
@NickIliev commented on [Mon Oct 08 2018](https://github.com/NativeScript/android-runtime/issues/1184)

_From @suparnavg on October 8, 2018 7:43_

**Is your feature request related to a problem? Please describe.**
The current documentation on [publishing to android](https://docs.nativescript.org/angular/tooling/publishing/publishing-android-apps#release-certificate) does not have any guidance for using the [Google Play App signing](https://developer.android.com/studio/publish/app-signing#google-play-app-signing) flow. Requesting some clarity on this issue because google's app signing has many benefits over creating and managing your keys personally.

An issue was opened previously #4888  but has since been closed without enough clarity..

**Describe the solution you'd like**
Questions:
1. Is Google Play App Signing compatible with how NS apps are signed before release?
2. If so, what is the process to do it?

Thanks a lot!

_Copied from original issue: NativeScript/NativeScript#6368_

---

@suparnavg commented on [Wed Oct 10 2018](https://github.com/NativeScript/android-runtime/issues/1184#issuecomment-428431584)

@NickIliev can you please tell us if this issue is resolvable / is on the roadmap, or would it be better to proceed with the existing app signing technique (managing keys personally).

Thanks in advance!

---

@NickIliev commented on [Wed Oct 17 2018](https://github.com/NativeScript/android-runtime/issues/1184#issuecomment-430586979)

@suparnavg  Currently we are supporting with the existing signing workflow. WIll mark this one as a feature in the CLI repository.

**Comment by yahyaKacem** [comment]
Any news on this issues?
if resolved is there a doc that shows how to do this?

**Comment by KristianDD** [comment]
Hi @yahyaKacem,
We tested the "App signing by Google Play" and it seems to work as expected and as described in the [Google documentation](https://developer.android.com/studio/publish/app-signing).

**If you are releasing a new application that hasn't been published** before, the workflow is pretty straight forward. You create an upload key and sign your application with it.
`tns build android --release --key-store-path <path-to-your-upload-keystore> --key-store-password <your-upload-key-store-password> --key-store-alias <your-upload-alias-name> --key-store-alias-password <your-upload-alias-password>`

Then you create your new app in "Play Console" and when you get to publishing the first version you will be given an option to use "App signing by Google Play". On this step you can upload a ".pepk" file containing the certificate for signing the application or you can choose the option "Play Console" to generate a new signing key. This is the key that will be used to sign the application for the Play Store.

Then you just upload the `.apk` and the "Play Console" will detect and save the upload certificate. From this point on you should use the upload key to upload this application.

**If the application has already been published** with the signing certificate, the steps are a little different. When uploading the new version you can opt in to "App signing by Google Play" and then should follow the steps that "Play Console" lists. Choose "Export and upload a key from a Java keystore". Download the `PEPK` tool and execute the command you see in the instructions in "Play Console".

Now your signing key will be also used as upload key. You can contact "Google Console" support to change the upload key, so that it is different from the one used to sign your application.

You can also check this [Stack Overflow answer](https://stackoverflow.com/a/54688197/10622723) for more information on the workflow with existing app. And if you need info how to generate a key you can check this [Stack Overflow answer](https://stackoverflow.com/a/15330139/10622723).
