### ISSUE TITLE
Extra file is not transferring during livesync

### ISSUE THREAD

**Issue by webleaf** [NativeScript/nativescript-cli#4082]
**Environment**
 - CLI: 4.2.4
 - Cross-platform modules: 4.2.1
 - Android Runtime: 4.2.0

**Describe the bug**

I have SQLite db file in `app` dir named `schema.db`. When I make any changes in it, CLI detect it and livesync process run. In console I see:
```
Successfully transferred schema.db.
Refreshing application...
```
Then my app (on every app start) make copy of this db file from app dir to corresponding place via `nativescript-sqlite` plugin.
But it actually turns out that I am working with the old version of the my db file.
Then I try to connect other device and make `tns run android`. And again, the old version of the db file is in a build.
But if I remove `platforms` dir and make clean run, new db file appears in a build.

**Comment by KristianDD** [comment]
Hi @webleaf ,
After investigating the issue I found why there is an outdated data inside the `nativescript-sqlite` plugin. Livesync does indeed transfer the file to the device in the application folder, but `nativescript-sqlite` plugin reads the .db file from different location - the application assets. The line of code inside the plugin that does that is [here](https://github.com/NathanaelA/nativescript-sqlite/blob/4d6d4babe06b01e54b0c2ada97416e0be907860b/src/sqlite.android.js#L855). I would recommend logging an issue in the plugins GitHub repository in order to start a discussion if this is the right approach.

You might also want to check [this issue](https://github.com/NathanaelA/nativescript-sqlite/issues/37), which is similar to what you need with the difference that the discussion is mainly about getting the `.db` file from a remote server.

In order to explain why these files are different I will have to describe in short how LiveSync and parts of NativeScript work on Android. When you build an `.apk` the NativeScript app files are inside the assets of the application. When the application is started the Android Runtime extracts them inside the application folder of the device on the first ever start of the application. After that the V8 engine and the application itself use the .js, .css, .xml files from there. You can see the extraction logic [here](https://github.com/NativeScript/android-runtime/blob/master/test-app/app/src/main/java/com/tns/RuntimeHelper.java#L101).

Livesync updates the files inside the application folder that the runtime created on the first ever run, but not the ones that were initially included inside the application assets.

You can verify that the file is updated on the device by using the Android Studio [Device File Explorer](https://developer.android.com/studio/debug/device-file-explorer) or using the following shell command:
`adb -s <your device id> shell "run-as <your app id> cat /data/data/<your app id>/files/app/<your .db file>" > ./fileFromDevice.db`.

**Comment by KristianDD** [comment]
Hi @webleaf ,
Good job on creating a PR. Thank you for contributing to the community. 

Closing the issue here, feel free to reopen it if any further fixing/investigating is needed from NS CLI perspective.
