### ISSUE TITLE
run tns preview get some error

### ISSUE THREAD

**Issue by yoking-shi** [NativeScript/nativescript-cli#4159]
create an new vue project, then run `tns preview`, scan the qr code,
get some error

![image](https://user-images.githubusercontent.com/39612025/48819116-39279d00-ed89-11e8-9d4e-30f2ae8aea32.png)

but when i run `tns run ios --bundle`, the app display success.

how can i solve the question.

**Comment by yoking-shi** [comment]
![image](https://user-images.githubusercontent.com/39612025/48820955-28c7f000-ed92-11e8-9a4e-23b47186218f.png)

**Comment by DimitarTachev** [comment]
Hi @yoking-shi,

Thanks for reporting this limitation. You are getting this error because currenctly only our webpack plugin can compile the Vue projects. For this reason, we have [a pull request ](https://github.com/nativescript-vue/nativescript-vue/pull/361)in the `nativescript-vue` plugin for validating this option and avoiding such runtime exceptions.

In other words, you should always use `--bundle` in your NativeScript Vue projects.

**Comment by yoking-shi** [comment]
@DimitarTachev 👌Thank you :)

**Comment by yoking-shi** [comment]
@DimitarTachev By the way, how can I change the preview feature?I still want to try this feature. 🤔

**Comment by DimitarTachev** [comment]
@yoking-shi, just use `tns preview --bundle` :)

**Comment by yoking-shi** [comment]
@DimitarTachev ,This command will prompt the same error,
So I asked questions again
