### ISSUE TITLE
wrong message if you delete app's folder and run command with `--path` in it

### ISSUE THREAD

**Issue by miroslavaivanova** [NativeScript/nativescript-cli#4280]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.0
 - Android Runtime: 5.1.0
 - iOS Runtime: 5.1.0

**Describe the bug**
If you try to run app in non-project folder with `--path` in command without existing folder, you will see exception and you couldn't understand what is the problem.

**To Reproduce**
1. `tns create app`
2. navigate to folder different from app's folder
3. run `/folder/tns run ios --path app`
4. you will see message: `Cannot read property 'targetedOS' of null`

**Expected behavior**
correct error for non existing folder

**Comment by jamesgeorge007** [comment]
@miroslavaivanova @rosen-vladimirov I would like to take this up :clap: I'm new here and am not that aware of the code-base. It would be great if you could point me to the right files to work upon :+1:

**Comment by Fatme** [comment]
@jamesgeorge007,

Sorry for the late replay!

In order to implement this you need to change this line https://github.com/NativeScript/nativescript-cli/blob/master/lib/commands/run.ts#L69. `$projectDataService` should be injected here instead of `$projectData`.
```
$projectDataService: IProjectDataService
```

After that you need to change [canExecute function here](https://github.com/NativeScript/nativescript-cli/blob/master/lib/commands/run.ts#L77):
```
public async canExecute(args: string[]): Promise<boolean> {
    const projectData = this.$projectDataService.getProjectData();
}
```
After that you should change all occurrences of `this.$projectData` with `projectData` inside `canExecute` function.

As the `this.$projectDataService.getProjectData()` internally validates the `path to the project`, it''ll throw an error when the project path doesn't exist - https://github.com/NativeScript/nativescript-cli/blob/master/lib/project-data.ts#L93.

Feel free to write back if you need more information.

**Comment by jamesgeorge007** [comment]
@Fatme There are couple of errors being thrown as part of the CI tests such that the `projectDataService` is never being used as well as `projectData` is not defined. 
What's going wrong :thinking:

**Comment by jamesgeorge007** [comment]
@Fatme Kindly have a look at #4538 and let me know your suggestions :smiley:

**Comment by Fatme** [comment]
@jamesgeorge007,

Thank you for the contribution!

I merged your PR. If this is your first contribution to NativeScript, you are eligible for our NativeScript First-Time Contribution program. More info can be found [here](https://www.nativescript.org/blog/nativescript-first-time-contribution-contest-continued-and-extended).

We'll be more than glad to help you, if you'd like to fix another bug or implement some feature.
