### ISSUE TITLE
Provide Extensibility to Include iOS Native Extensions in NativeScript Apps 

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#4393]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to add App Extensions to my NativeScript application for iOS. For example, I would like to use Share extension, Today widget, etc.
More information for the extensions can be found here: https://developer.apple.com/app-extensions/

**Describe the solution you'd like**
Allow using native iOS Extensions in NativeScript app, i.e. place their source code (Objective-C) under source control, for example in `App_Resources` directory.

parent to https://github.com/NativeScript/nativescript-cli/issues/4391
parent to https://github.com/NativeScript/nativescript-cli/issues/3965

**Comment by tdhman** [comment]
Hello,

I run into this issue then by following the post [nativescript-ios-imessages](https://github.com/NativeScript/nativescript-ios-imessages), I'm able to add the share extension into iOS project with the application source code + add 1 view controller for the share extension target that can be created in `js` (as described in the post above)
Therefore, I would like to reuse a module / function from the application target to do the sharing task in without recoding the function because I have the same function that works in the main application. However, I do not able to do this with `NativeScript-Vue` since it packages the code into 1 bundle file. I am not able to reuse the module defined in the app bundle.

My suggestion is that NativeScript can support iOS extension with `js` source code and share code base between the application target and the share extension target. That would be great because we only need to do the code in js.

**Comment by KristianDD** [comment]
Hi @tdhman ,
The feature for using NativeScript framework inside the extension is still under consideration. The main reasons for that are the limitations that iOS App Extensions have. One of the main ones is the memory limitation, which once exceeded will just kill the extension process runtime. Each extension has different memory footprint limitation, but we still need to investigate in which extensions we have enough room for running the runtime. In this [Stack Overflow thread](https://stackoverflow.com/questions/37361261/ios-app-extensions-maximum-memory-budget) you can read about some cases where developers had hit the memory limit with pure native extensions.

The other issue is that extensions have strict limitations to which APIs they can access. Same restrictions apply to frameworks embedded inside the extension target. Reference [here](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW1).

Will update you once we have more information on the status of this feature.

**Comment by KristianDD** [comment]
Logged a [separate issue](https://github.com/NativeScript/nativescript-cli/issues/4540) for research of embedding NativeScript framework in iOS App Extensions. Closing this issue as the feature it describes is already finished and released.
