### ISSUE TITLE
com.tns.NativeScriptApplication cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by max-pro** [NativeScript/nativescript-cli#4474]
Hello All,
 i'm trying to use android native payTM plugin in my nativescript application.
but i'm getting error for this operator.

```
System.err: java.lang.ClassCastException: com.tns.NativeScriptApplication cannot be cast to android.app.Activity
System.err:     at com.paytm.pgsdk.PaytmPGService.startPaymentTransaction(PaytmPGService.java:152)
```

Native android code:
`Service.startPaymentTransaction(this, true, true,callback);`

my nativescript code:
const application = require("application");
`Service.startPaymentTransaction(application.android.context, true, true,callback);`

another way i try
```
const utilsModule = require("tns-core-modules/utils/utils");
Service.startPaymentTransaction(utilsModule .ad.getApplicationContext(), true, true,callback);
```

**Comment by NickIliev** [comment]
@max-pro the error is pretty much saying it all `com.tns.NativeScriptApplication cannot be cast to android.app.Activity`

So you are passing the application context instead of the current activity.
Try passing the current activity via the `foregroundActivity` property

```TS
application.android.foregroundActivity
```

Closing the issue as how-to related and as non-related to CLI.

**Comment by NickIliev** [comment]
@max-pro as a side note - there is this plugin called [nativescript-paytm](https://www.npmjs.com/package/@nstudio/nativescript-paytm)
