### ISSUE TITLE
Error: Could not find module 'inspector_modules.js' in shared-project

### ISSUE THREAD

**Issue by tahir-jamil** [NativeScript/nativescript-cli#4628]
I'm using shared project in nativescript angular and debugging is not working fine on it 

CONSOLE WARN Loading inspector modules failed:  Error: Could not find module 'inspector_modules.js'. Computed path '/Users/m.tahir/Library/Developer/CoreSimulator/Devices/76757D36-3B6F-4988-9003-DE308F52EAC0/data/Containers/Bundle/Application/E98FF00C-3716-4C5D-9D30-15A312A05ED8/tusharedapp.app/app/tns_modules/inspector_modules.js'.

**Comment by DimitarTachev** [comment]
Hi @tahir-jamil,

Such issue was fixed in the latest versions of `nativescript-dev-webpack`. I suggest you update the plugin (`npm i nativescript-dev-webpack@latest --save-dev`) and execute its update script (`./node_modules/.bin/update-ns-webpack --configs`) in order to get the latest version of our `webpack.config.js`.

If the issue is still reproducible, please follow the issue template and provide us with more details about your dependencies versions and the content of your config files.

**Comment by tahir-jamil** [comment]
CONSOLE WARN Loading inspector modules failed:  Error: Could not find module 'inspector_modules.js'. Computed path '/Users/m.tahir/Library/Developer/CoreSimulator/Devices/E175A09A-7E5E-4217-8B9F-EF7D6FA378D1/data/Containers/Bundle/Application/B0B45CF4-61E7-4AF5-BA09-62A2696C3B0C/tusharedapp.app/app/tns_modules/inspector_modules.js'.

**Comment by tahir-jamil** [comment]
i have updated the webpage but issue still remains

**Comment by tahir-jamil** [comment]
Hi @DimitarTachev  updating webpack using your command npm i nativescript-dev-webpack@latest --save-dev will fix my issue thanks a lot man
