### ISSUE TITLE
libNativeScript.so for x86_64 CPU architecture missing for Android

### ISSUE THREAD

**Issue by kzimny** [NativeScript/nativescript-cli#4833]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.1.0
 - Cross-platform modules: no
 - Android Runtime: 5.4.0
 - iOS Runtime: 5.4.2
 - Plugin(s): no plugins

**Describe the bug**
libNativeScript.so for x86_64 CPU architecture missing in .\platforms\android\app\build\outputs\apk\release\app-release.apk\lib\x86_64 folder

**To Reproduce**
tns create my-angular-app --ng
cd my-angular-app
tns platform add android
tns build android --release --key-store-path ../InstallationFiles/android/idkd-release-key.keystore --key-store-password MyStorePassword --key-store-alias MyAppXYZ --key-store-alias-password MySecretPassword

**Expected behavior**
folder .\platforms\android\app\build\outputs\apk\release\app-release.apk\lib\x86_64 with libNativeScript.so for 64 Bit CPU architecture should be created

**Sample project**
no, see steps to reproduce

**Additional context**
My app.gradle looks as follow:
```
android {
  defaultConfig {
    minSdkVersion 17
    generatedDensities = []
    ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
  }
  aaptOptions {
    additionalParameters "--no-version-vectors"
  }
}
```

**Comment by KristianDD** [comment]
Hi @kzimny,
This issue is already logged inside NativeScript Android Runtime repository [here](https://github.com/NativeScript/android-runtime/issues/1419) and will most probably be fixed for one of the next NativeScript releases.

The application should still fallback to the 32bit library and work as expected. Closing issue here as it is not related to NativeScript CLI.
