### ISSUE TITLE
Combine JavaScript files in a single file in release builds

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/nativescript-cli#489]
On iPhone 5 about 50ms of 980ms of the startup time of the Cuteness sample (and similar on Android) is spent for requiring JavaScript modules.

This could be reduced if we combine (and optionally minify) all used JavaScript modules in release build.

**Comment by ligaz** [comment]
This could be somehow related to the transpilers support #493

**Comment by teobugslayer** [comment]
Maybe we can work with @mishoo and use the excellent Uglify.js lib?

**Comment by Alphapage** [comment]
The problem seems to come from how page.xml code behind is managed.
From my test, it seems page.xml needs page.js (ie page.css) to find methods...

So the limitation is how to tell page.xml where to get navigatedTo for example.
Something like this:
<Page codeFile="path/to/the/bundlefile.js" codeClass="Mynamespace.Myclass" navigatedTo="pageNavigatedTo"/>
or:
<Page codeFile="path/to/the/bundlefile.js" navigatedTo="Mynamespace.Myclass.pageNavigatedTo"/>

For now, I'm unable to use this kind of folder structure in my app:
- scripts (all .js files)
- views (all .xml files)
- styles (all .css files)
this could solve my problem too.

**Comment by blagoev** [comment]
This can probably negativly reflect on how you debug and/or/when get error reports from production apps

**Comment by PanayotCankov** [comment]
[Source Maps, Source Maps everywhere... We need to support these for obfuscators, transpilers etc.](http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/)
[Meanwhile we've spent some time profiling the app and improved our caching.](https://github.com/NativeScript/ios-runtime/pull/191)

XML code-behind will be interesting, source maps won't handle that easily. They map the location in the generated JavaScript to the original source, however for the XMLs we will need a mapping that works the other way around.

**Comment by jasssonpet** [comment]
This is now possible with https://github.com/NativeScript/nativescript-dev-webpack

**Comment by jasssonpet** [comment]
Further things to research:
* HotReload (https://github.com/webpack/docs/wiki/hot-module-replacement-with-webpack)
* Debugger integration (including TypeScript and source maps)
* Packing and requiring other resources (XML, CSS) from within the bundle
* LiveSync - how will it work with the bundle
* Encryption - verify the plugin works with the bundler
* Android snapshot - how will it work with the bundle

**Comment by jasssonpet** [comment]
Debugging issues:
* https://github.com/NativeScript/nativescript-vscode-extension/issues/55
* https://github.com/NativeScript/nativescript-vscode-extension/issues/56
* https://github.com/NativeScript/ios-runtime/issues/601
* https://github.com/NativeScript/nativescript-vscode-extension/issues/59

**Comment by dtopuzov** [comment]
This should be resolved by [nativescript-dev-webpack](https://docs.nativescript.org/best-practices/bundling-with-webpack).
