### ISSUE TITLE
Android SDK 29 support

### ISSUE THREAD

**Issue by KristianDD** [NativeScript/nativescript-cli#4926]
**Is your feature request related to a problem? Please describe.**
NativeScript should be able to build applications with Android SDK29

**Describe the solution you'd like**
The Android SDK29 should be chosen by default if available on the machine.

**Describe alternatives you've considered**
No alternatives

**Additional context**
There are currently two places where we keep the compatible Android SDK versions - NS CLI and NS Doctor. This makes the update difficult and no straight forward. There is also a lot of repetition of code in android-tools-info modules inside the CLI and NS Doctor. For future updates it will be beneficial to extract the logic at one place.

**If the targeted device is APK Level 29(Android 10) the application should use the `next` version of NativeScript Adnroid Runtime!**

**Acceptance Criteria**
Valid values for --compileSdk are >=28. (should be installed)
Valid values for --sdk are >= 17 <=29 (corresponds to targetSdk and not mandatory to be installed)
Valid Android build tools on the machine are >=23 (should be installed)

- [x] 1. SDK 29 should be chosen by default if available on the machine. You can verify that SDK 29 was used by using Analyze APK inside Android Studio and check the values inside Manifest.xml.
- [x] 2. Deploy, run, debug and test should work as expected. - test against an API 28 and API 29 devices.
- [x] 3. Validations from the doctor for `tns run android` should be the same as in previous version. Can add a plugin that needs build (has `Manifest.xml` and `include.gradle` but no `.aar` in package). This can be emulated installing `nativescript-mapbox`, deleting the `.aar` file from `node_modules/nativescript-mapbox` and then copy the `Manifest.xml` from [here](https://github.com/EddyVerbruggen/nativescript-mapbox/tree/master/src/platforms/android).
  - [x] a. `tns build android --compileSdk 16` where SDK16 is installed
  - [x] b. `tns build android --compileSdk 25` where SDK25 is not installed
  - [x] c. Rename android sdk folder.
  - [x] d. Remove all SDKs that are supported by NS >= 17 <=29
  - [x] e. Remove SDKs above SDK 27
  - [x] f. When SDK 28 and 29 are available, if project is with Android Runtime 6.0.0, SDK28 should be used and when project is with Android Runtime 6.1.0 SDK29 should be used.
- [x] 4. Same as 3 but with `tns plugin build` - should clone a plugin that has `platforms\Android\Manifest.xml`. - for example [this one](https://github.com/EddyVerbruggen/nativescript-mapbox).
  - [x] a. `tns plugin build --compileSdk 16` where SDK16 is installed
  - [x] b. `tns plugin build --compileSdk 25` where SDK25 is not installed
  - [x] c. Rename android sdk folder.
  - [x] d. Remove all SDKs that are supported by NS >= 17 <=29
  - [x] e. Remove SDKs above SDK 27

**Comment by rosen-vladimirov** [comment]
Due to issues with Android Runtime when building the applications with Android SDK 29 and running them on devices (emulators) with SDK 29 that are fixed in Android Runtime (`tns-android` package) 6.1.0, the following logic is implemented in CLI:

<table>
  <tr>
    <th>SDK Installed</th>
    <th>tns-android &lt; 6.1.0</th>
    <th>tns-android 6.1.0 or later</th>
  </tr>
  <tr>
    <td>Android SDK 28 and 29</td>
    <td>CLI will use SDK 28</td>
    <td>CLI will use SDK 29</td>
  </tr>
  <tr>
    <td>Android SDK 28</td>
    <td>CLI will use SDK 28</td>
    <td>CLI will use SDK 28</td>
  </tr>
  <tr>
    <td>Android SDK 29</td>
    <td>CLI will not allow build and throw an erro</span>r</td>
    <td>CLI will use SDK 29</td>
  </tr>
</table>

Description of the table:
* In case you have both Android SDK 29 and 28 installed, but you are still using Android Runtime (`tns-android`) before 6.1.0, CLI will use SDK 28.
* In case you have both Android SDK 29 and 28 installed, and you are using Android Runtime (`tns-android`) 6.1.0 or later (including pre-release versions of 6.1.0), CLI will use SDK 29.
* In case you have only Android SDK 28 installed, and you are still using Android Runtime (`tns-android`) before 6.1.0, CLI will use SDK 28.
* In case you have only Android SDK 28 installed, and you are using Android Runtime (`tns-android`) 6.1.0 or later (including pre-release versions of 6.1.0), CLI will use SDK 28.
* In case you have only Android SDK 29 installed, and you are still using Android Runtime (`tns-android`) before 6.1.0, CLI will throw an error that this combination is not supported. In this case you can either install Android SDK 28 or update your Android Runtime version to latest version (`tns platform remove android && tns platform add android@latest`).
* In case you have only Android SDK 29 installed and you are using Android Runtime (`tns-android`) 6.1.0 or later (including pre-release versions of 6.1.0), CLI will use SDK 29.

**Comment by endarova** [comment]
In case you have only Android SDK 29 installed, and you are still using Android Runtime (tns-android) before 6.1.0 there is not descriptive error  that this combination is not supported

**Comment by JamesPJ** [comment]
> In case you have only Android SDK 29 installed, and you are still using Android Runtime (tns-android) before 6.1.0 there is not descriptive error that this combination is not supported

I'm bit confused with the statement **there is not descriptive error that this combination is not supported**.

I'm having NS 5.4 and the app built on angular 4. But, if I build the app with taregetSDK 29. The installed app start crashing.

Also I've tried upgrading to latest NativeScript version. But, I noticed it is required to have the latest version of Angular. And my code needs lot of modificatons. Let me know is there any easy migration path if it is mandatory to have the latest NS cli.

**Comment by jamescodesthings** [comment]
If anyone ends up here because they have a build still based on 5.4 they have to support whilst updating is underway I found that the crash on startup issue is https://github.com/NativeScript/android-runtime/issues/1458 which was not applied to the 5.x branches.

You can check out android-runtime at the version you need and cherry-pick the commit in to produce a build of 5.4.0 that works on SDK level 29.

**Comment by NathanaelA** [comment]
@jamescodesthings - NS 5 is several years old.    If you have a support contract with nStudio, we would be willing to build you a custom version -- However, you should also try using a NS 6.x runtime with your NS5 app, it probably will work, most the time they are actually backwards compatible...

**Comment by leena-bhise** [comment]
@JamesPJ, I'm facing the same issue. Is this issue resolved if yes, So let me know what steps you follow for resolved this issue?

**Comment by JamesPJ** [comment]
@leena-bhise Yes, but I had to upgrade to `NS{6}`

**Comment by leena-bhise** [comment]
@JamesPJ, I also upgraded to NS{6} and follow the steps below:

- Removed node_modules and platforms and hooks and ./gradle folder
- Installed the NS{6}
- Then run `npm i`
- Then run `tns migrate`
- Then `tns run android`

but still facing the issue. Let me know if I'm missing something.

**Comment by JamesPJ** [comment]
@leena-bhise I'm not sure what issue you are facing. But, I had faced issue with certain cli versions. Below are my current cli versions.

```
tns-android has 6.5.3 version
tns-ios has 6.5.2 version
```

**Comment by jamescodesthings** [comment]
@leena-bhise This particular issue was present in the 5.x versions of the android platform only. Upgrading is the ideal path. We're currently progressing through an upgrade to v7.x.

It's likely you're facing a different issue as it was patched in: https://github.com/NativeScript/android-runtime/issues/1458 which is in the 6.5.3 version of ns-android you're using.
