### ISSUE TITLE
Apple Watch app building

### ISSUE THREAD

**Issue by ReeceReynolds** [NativeScript/nativescript-cli#4993]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4.0
 - Cross-platform modules: 5.4.2
 - iOS Runtime: 5.4.2

**Describe the bug**
I'm trying to add an Apple Watch app to a NativeScript project I am working on. I have followed the documentation on how to add the Watch app to the App_Resources although the project won't build and I receive the following error:
`Unable to apply changes on device: (Device UDID). Error is: Expected "/*", ";", or [ \t\n\r] but "E" found..`
Both the iOS app and Watch app build and run as expected prior to copying the Watch app into the resources.

**Expected behavior**
Watch app and iOS app build successfully.

**Additional context**
I usually run the project with `tns run ios --bundle` but have tried without bundle. I have also erased all content from the emulator, tested on personal iPhone and Apple Watch and restarted my machine but no luck.

After reading around I believe this could be do with signing stated here #4589
> The watch app inside NativeScript application support only Automatic code signing. Any provision configuration inside App_Resources/iOS/build.xcconfig will be ignored. And the application build will most probably fail.
I am signing the project and have my provisional profiles set up with my devices. Watch app is set to "Automatically manage singing" for both apps.

**Comment by KristianDD** [comment]
Hi @ReeceReynolds,
I am sorry for the late response. We were concentrating our efforts on delivering the NativeScript v6.1.0 release.

I have encountered the same error lately and it turned out to be a bug that manifests itself, when the Apple Watch Extension contains an `.entitlements` file and the extension has a space in the name(which is by default when created in Xcode). As a workaround you should rename the extension, so that it doesn't contain a space in the name.
1 Rename the extension folder
2 Rename the `.entitlements` file to match the extension
3 Inside the `Info.plist` of the extension, change all occurrences of the extension name.

You can check [this issue](https://github.com/NativeScript/nativescript-cli/issues/5005) for more information and to track the progress of the fix.

**Comment by ReeceReynolds** [comment]
Thank you, fixed the error message I was getting!
