### ISSUE TITLE
Configure entry point

### ISSUE THREAD

**Issue by Alphapage** [NativeScript/nativescript-cli#508]
Hello,

It seems the only entry point file available is app.js.
Is it possible to point to another one such as /folder1/newEntry.js for example?

Thanks in advance for your answer.

**Comment by Fatme** [comment]
Hi @Alphapage,

You can add `package.json` file in your app with the following section: 
```
{
  main: "path to your entry point"
}
```

**Comment by Alphapage** [comment]
You learn me something today thank you. :+1: 
But I'm unable to make databinding working, I want this kind of folder structure:
scripts
styles
views

I tried to tweak:
 application.mainModule = "./views/main-page";
without success, each time I tap, no message is displayed.

**Comment by Nathanaela** [comment]
Well, I can tell you why it isn't working; the **issue** is with your structure.  

When the runtime loads the "**./views/**main-page.js" it will then look for "**./views/**main-page.xml" and "**./views/**main-page.css" in the exact same **/views/** folder.    Basically on any load of any page; it will look for all three files in the exact same folder.

However, with that said -- with a short amount of work you can easily hook the api responsible for this (I use this exact technique for my nativescript-updater module) and easily modify the logic without actually changing any of the code in the tns_modules folder.     

**Warning**:  Unless you are doing patches that you are planning on committing -- you should **not** change **anything** in your apps / **tns_modules** folder.  When you do any upgrades **everything** in that folder will be replaced with the new runtime code..     So it is MUCH better to hook the api; so that you can update the runtimes at will, and still be running fine.

**Comment by Nathanaela** [comment]
I should mention the api you should hook into is file-name-resolver.resolveUpdatePath, with it you can control where the module piece is loaded from.

**Comment by Alphapage** [comment]
OK I understand now.
So I can't concat my js files to a single .js file because of this behaviour.
It would be great to be able to specify the path to the .xml file something like:
frames.topmost().navigate({
        moduleName: "details-page",
        context: appViewModel.redditItems.getItem(args.index),
        path: "./views/details/details-page.xml"
    });
I don't know how it would be possible to define in mainModule!

**Comment by hshristov** [comment]
Hi @Alphapage,
In my opinion it is better to have xml, css & js in one folder. It brings modularity in your app especially if you have multiple pages.
But it seems it is a common request to have xml in views, css in styles and js in scripts folders so we will plan it for one of the next releases.
