### ISSUE TITLE
Typo in splash screen filenames

### ISSUE THREAD

**Issue by tkrevh** [NativeScript/nativescript-cli#5118]
Should be Portrait, not Portarit
https://github.com/NativeScript/nativescript-cli/search?q=Portarit&unscoped_q=Portarit

**Comment by rosen-vladimirov** [comment]
Hey @tkrevh ,
Thank you for the report. The incorrect name is intentional for compatibility with some of the templates which had incorrect names. These incorrect names are not used for generation of images when you do not have them in the App_Resources, so they should not cause any troubles on your side. 
I'm closing this issue, but feel free to reopen it in case you have some issues with the images.
