### ISSUE TITLE
'tensorflow/contrib/lite/kernels/register.h' file not found

### ISSUE THREAD

**Issue by sakonwantarn** [NativeScript/nativescript-cli#5123]
Xcode version 11.2

<img width="1280" alt="Screen Shot 2562-11-10 at 16 02 59" src="https://user-images.githubusercontent.com/54447284/68541638-7dfe7680-03d4-11ea-8913-a401a7f19a4a.png">

I follow this tutorial **https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2-ios/?fbclid=IwAR3IISO8dNpomKEVfumkg01M3Xj7MDsHJE1PGg-NdiiNhGg2HSggZx9eUqs#4**

but can't run Xcode from this bug. please help

**Comment by rosen-vladimirov** [comment]
Hey @sakonwantarn ,
This is NativeScript CLI repository. It seems your problem is not related to [NativeScript](http://nativescript.org) , but if you are interested in our technology, you can try it in our [Playground](https://play.nativescript.org). 
For your current question, you can try asking in StackOverflow.
