### ISSUE TITLE
LiveSync support

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#523]
We will be enabling LiveSync support for NativeScript application and we plan to roll this out in a couple of stages.

### LiveSync commands
- [x] `livesync` - This command will update all your `app` files and will restart the app on the device.
- [x] `livesync --watch` - This command will watch for file system changes, sync only the changed files on the device and finally restart the app after the sync.
In the 1.2 time frame we plan to have first-stage LiveSync implementation. To work, it will restart the application. 

### Technical details 
* The following location will be used for storing and updating the `app` files: 
  * Android - `/data/local/tmp/...`and `/data/data/...`. 
  * iOS - `~/Library/Application Support/LiveSync`.
* We need to restart the app in order to guarantee that the application state will not be corrupted. This is highly critical on iOS because it relies on singleton instances of many application level objects.

**Comment by Nathanaela** [comment]
Awesome, I would love to see this natively supported from the command line -- A couple things;

1. Since you are doing the "safer" route (vs what I do with my current version of my LiveSync plugin) -- I would recommend you save the frame.navigate information and reopen to the same place.   I would be pretty annoyed if I was doing changes; and kept having to navigate several levels deep to re-open the window I changed to see the changes.    I'm currently looking at possibly re-opening the full hierarchy on a restart so that the application state is pretty close to what it was; but I'm not sure a perfect way to do this since Frame 2 could have text fields filled in that called Frame 3; and a restart would clear any fields on Frame 2.

2. If the JS file has NOT been loaded yet; don't restart the app.    You'll notice my plugin ALWAYS checks to see if the screen is the current screen before it does anytype of inplace reload.  

3. I've recently added a feature to my livesync to allow the developer to choose which files force a restart; so that way if I'm editing like a singleton file; the app will restart rather than do my in place reload.   So at the point in the future you enable smarter livesync stuff; this is one way I handle it.

**Comment by ligaz** [comment]
Thanks for your feedback @Nathanaela. Here are my comments:

1. Saving the current frame might work for some applications but will not work for others that depend on state. For example imagine an app that has a login screen. The ideal case will be for users to specify what kind of sync they want: `restart`, `refresh` (hard reload) or `reload`.

2. That will be a good optimization we can apply in one of the next iterations. I have added it to the list.

**Comment by Nathanaela** [comment]
@ligaz yeah, I know that is why I said I didn't know a perfect way to handle this; I've considered several options because of what I do with my livesync.   But nothing is bulletproof.     I'm adding the feature to set a flag when I call the screen navigate function called "liveSync: true" so that the developer can set any extra data they might need to on my reload of the screen.  

I would still recommend this as a feature; because if the app is doing a restart; I might not need to login to work with screen three levels deep if I'm passing the same data back to it via the navigate function.     

Is this feature going to show up in soon; or is this still a ways off?

**Comment by ligaz** [comment]
Yes this feature is already available in master and the v1.2 scope for will be publicly available when we officially release v1.2.

**Comment by nmladenov** [comment]
reopening due to these issues: https://github.com/NativeScript/nativescript-cli/issues/654
