### ISSUE TITLE
Have to delete app off phone to update

### ISSUE THREAD

**Issue by curtiscarlson** [NativeScript/nativescript-cli#5309]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.0
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime: 13.4.1
 - Plugin(s): nativescript-plugin-firebase 

**Describe the bug**
Only way to update changes is to delete the app completely.  On command line, "tns run ios" goes through the motions but the phone is unaffected.  In sidekick, same thing, nothing happens.  I can't even just rebuild without deleting the app off the phone.  It acts like it builds but I can tell the app is unaffected.  Often after deleting and rebuilding the app I still get an error "Build failed.  Cannot read property 'pid' of undefined.  But clicking "Run on Device" a second time fixes that bug.  Live update / Hot reload has never worked for me since installing firebase.  

**To Reproduce**
click "Run on Device" or use "tns run ios"

**Expected behavior**
app builds, loads onto phone and refreshes

**Sample project**
not possible

**Additional context**
coming back from 2 month break away from developing this app.  Had to upgrade Iphone OS, MacOs, Xcode, npm, and nativescript.  That all took a day.  Still can't get it to work right.  This happens every time apple updates something.

**Comment by NathanaelA** [comment]
Actually it sounds like you changed your package.json name of the project.  If you do that, then the package name no longer matches the application name and so then the tooling that uses the package.json doesn't match and so it fails to replace and start it properly.

Typically, the easiest way to fix this issue is to delete the "platforms" folder and then do another build of your application.   (You might need to delete the app off the phone this first time too, but then all future times it should be syncing properly).
