### ISSUE TITLE
filter device console for "CONSOLE LOG" ?

### ISSUE THREAD

**Issue by curtiscarlson** [NativeScript/nativescript-cli#5310]
**Is your feature request related to a problem? Please describe.**
"I'm always frustrated when" I have to sift through pages of unintelligible crap in order to find the console log output that I actually need 

**Describe the solution you'd like**
Only outputs CONSOLE LOG notices

**Describe alternatives you've considered**
becoming a landscaper

**Additional context**
this would be nice in sidekick as well

**Comment by NathanWalker** [comment]
@curtiscarlson landscaping is fun too :) -- When using `adb` on Android or iOS device log we couldn't agree more, definitely a filter needed. 

@NathanaelA perhaps we could add a flag to command line which would auto filter to only {N} related console.log's?

**Comment by NathanaelA** [comment]
@NathanWalker @curtiscarlson - `TNS` by default should already be filtering to only the output of the CONSOLE LOG output  on Android.   If you look at the below picture you will see the default output for `tns run android` on the left.      On the right, `adb` and `tns device log` will not filter anything because it is designed to display all messages as the filtering can eat important messages.

![image](https://user-images.githubusercontent.com/850871/83373386-c17afb00-a38d-11ea-8bdc-4c19e62aa441.png)

 However, if you prefer to use adb; when I use it I typically do it in two passes:
`adb logcat | grep TNS`
This will give me the process number like this:

![image](https://user-images.githubusercontent.com/850871/83373576-7ca39400-a38e-11ea-994a-3413191a636f.png)

And then I hit CTRL-C and then type `adb logcat | grep 30180` because I only want messages that are generated by my app.

**Comment by NathanWalker** [comment]
@NathanaelA curious about iOS here -- only when running against a real device (simulator output is okay) but device log is extremely noisy. Perhaps an easier way to filter output directly in the `tns` logs with ios devices connected?

**Comment by NathanaelA** [comment]
@NathanWalker - iOS is actually the much better platform for logging (imho), because it already does limit it to messages from messages caused directly by the application.   Where Android limits it to `console` commands.   I would love to change Android to be more like iOS.  :grinning:

This is actually very critical in that you will actually see any errors, crashes, OS related messages that your **application** **causes**; where on Android and the simulator these are almost always totally eaten.  I don't know how many times I've wasted time trying to figure out why something wasn't work because the simulator ate these messages.    I would much rather have some extra logging shown, and see these critical messages, then not see the critical message.   So I actually prefer to actually work against real devices on iOS, and emulators on Android.  :grinning: 

However, if you really want to filter this down on iOS to just "CONSOLE" messages; you can do this one of two ways:  
1. Start the console logger application and choose your device, and then type in `CONSOLE` as the filter.
2. use `idevicesyslog` and grep for "CONSOLE", like I outline in my blog at `http://fluentreports.com/blog/?p=545`
