### ISSUE TITLE
nativescript.config file has a wrong extension when generating a JS project

### ISSUE THREAD

**Issue by funder7** [NativeScript/nativescript-cli#5375]
**Environment**
 - CLI: 7.0.6

**Describe the bug**
When generating a new JavaScript project with `ns create`, the resulting project contains a `nativescript.config.ts` file, which is the only TS file in the project. I think that this was not left behind when the new config file has been introduced.

**To Reproduce**
```
ns create demo --js --appid org.nativescript.demo
```

**Expected behavior**
The generated project should contain a JavaScript configuration file: `nativescript.config.js`

**Comment by rigor789** [comment]
This is intentional - every project benefits from having a `ts` config because of the typings and autocompletion suggestions. The CLI takes care of parsing the config file, so there isn't a need to have any extra dependencies in a js project to support this.

If for some reason you still want to use a `.js` config file, you can manually rename the file and remove the typings - but we generally don't recommend it - you lose out on the convenience.

**Comment by funder7** [comment]
Ok... I thought that a Js project was not supposed to work with typescript files, to avoid adding typescript as a dependency.

**Comment by rigor789** [comment]
@funder7 Right - the nice thing is that the CLI can parse the file even if you don't have `typescript` as a dependency - it's not used either way.

**Comment by funder7** [comment]
Yep..that's ok so ;)
