### ISSUE TITLE
NDK now required or not?

### ISSUE THREAD

**Issue by saschaarthur** [NativeScript/nativescript-cli#5419]
**Environment**
 - CLI: 7.0.10

tns info
√ Getting NativeScript components versions information...
√ Component nativescript has 7.0.10 version and is up to date.
√ Component @nativescript/core has 7.0.11 version and is up to date.
‼ Update available for component @nativescript/ios. Your current version is 7.0.1 and the latest available version is 7.0.2-rc1.
√ Component @nativescript/android has 7.0.0 version and is up to date.

**Describe the bug**
Does NS need the NDK framework from google or not?
If im installing the 'wrong' version it complains, if i uninstall it continues without problems.

Is everything still working or is hidden failing somewhere?!

**To Reproduce**
- install all dependenys
- make sure ns doctor is fine
- install `sdkmanager "ndk;21.0.6113669"`
- delete platforms & node_modules
- npm ci
- ns run android --compileSdk 29 --no-hmr --env.uglify

Fails with: 
No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.0.6113669

- uninstall `sdkmanager --uninstall "ndk;21.0.6113669"`
- ns run android --compileSdk 29 --no-hmr --env.uglify

Now continues without complaining..

PS: seems to be introduced with NS-7, NS-6 was not bringing up this error till now (but i didnt verified it)

**Comment by NathanaelA** [comment]
In NS 7.x we upgraded the Gradle version; the Gradle version now has a built in "default" NDK version where it didn't before.  So when it detects your ndk it complains that it does not match what ndk that gradle version was tested with it complains and throws that error (we have no control over it, afaik.).    

https://developer.android.com/studio/projects/install-ndk#default-ndk-per-agp

If you have a newer version of the ndk; the document section above where I just linked to; will show you how you can set gradle to use a specific ndk version, so that when it goes to detect it will match and won't complain about it.

**Comment by saschaarthur** [comment]
Thanks for explaining where the issue comes from, but still the question remains, if the NDK is needed or not? 
Because it seems to work when theres no NDK installed at all?

**Comment by NathanaelA** [comment]
Clarification: No NDK is needed; it is just when Gradle detects you do HAVE a NDK with the wrong version, it complains because it doesn't match what it now wants your NDK version to be set to its new tested by google "default" version.
