### ISSUE TITLE
Android debugger on OS X has unexpected error

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#664]
Whenever I use the `tns debug android --debug-brk` command, regardless of project, I get this error:

```
Page.getResourceTree failed.
ReferenceError: process is not defined
```

Here's a screenshot:

![screen shot 2015-07-21 at 8 26 00 am](https://cloud.githubusercontent.com/assets/544280/8800627/66903f72-2f82-11e5-96db-aab3d81f9725.png)

Any idea what's up?

Thanks,
TJ

**Comment by slavchev** [comment]
Currently the CLI uses `node-inspector` as a debugger client for NativeScript for Android. We decided to use `node-inspector` mainly because it is a free debugger client for the V8 JavaScript engine. While NativeScript for Android runtime uses V8 engine it is not `nodejs`. For example, we do not expose `process` property of the `global` object. `node-inspector` assumes that it debugs `nodejs` and accordingly it injects a lot of `nodejs` specific JavaScript which makes use of the `process` property.

**Comment by Fatme** [comment]
Moved to android-runtime - https://github.com/NativeScript/android-runtime/issues/189
