### ISSUE TITLE
Better handling of package.json main configuration

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#670]
@jlooper and I have run across a few different npm modules that have a `"main"` of `"index"` in their `package.json`, instead of `"index.js"`—for example https://github.com/Sembiance/email-validator and https://github.com/snoj/email-validation.

This difference means that using one of these modules requires you to do:

``` js
var validator = require("email-validator/index");
```

instead of

``` js
var validator = require("email-validator");
```

Can the NativeScript CLI be changed to assume the .js suffix when it is not present? Furthermore, I'd like the CLI to support modules that do not have a `"main"` in their `package.json` at all. In these cases the NativeScript CLI should just use that module's `index.js` (if present).

Thanks.

**Comment by ligaz** [comment]
Hey TJ,

I completely agree that we should implement these suggestions in order to streamline the experience (mainly for people coming from Node.js background). However it might sound strange but this has nothing to do with the NativeScript CLI. :smile: 

This should be implemented in our `require` which is part of Android and iOS runtimes. I will discuss this with the teams today.

**Comment by tjvantoll** [comment]
Oh cool, I didn't realize that was determined at runtime. Let me know if you'd like me to move this issue over.

**Comment by Fatme** [comment]
Moved to https://github.com/NativeScript/ios-runtime/issues/270 and https://github.com/NativeScript/android-runtime/issues/190
