### ISSUE TITLE
Support building of XCode workspaces

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#686]
Allow the users to build Xcode workspaces instead of the project.

**Comment by Fatme** [comment]
Follow this steps in order to test this:
* Execute `pod` command. If the command is not found, execute `sudo gem install cocoapods`.
* Create new project and add ios platform.
* Create `Podfile` in `platforms/ios` folder
* cd platforms/ios
* pod install - this will produce .xcworkspace fiel
* build the project
