### ISSUE TITLE
File to add android platform on windows

### ISSUE THREAD

**Issue by qolby** [NativeScript/nativescript-cli#726]
i tried to add android platform after i have created a projec but it says the following error 
command failed: c://Windows/system........
"android" is not recognized as an internal or external command
operable program or batch file 

Please help

**Comment by dtopuzov** [comment]
It fails because "android" command is not in your path. 

Your PATH variable should include:
Path to tools directory in the Android SDK installation folder
Path to platform-tools directory in the Android SDK installation folder

For example: PATH=...;...;C:\Users\MyUser\AppData\Local\Android\android-sdk\tools;C:\Users\MyUser\AppData\Local\Android\android-sdk\platform-tools

For further info and troubleshooting please read this:
https://github.com/NativeScript/nativescript-cli#system-requirements
