### ISSUE TITLE
Support for CocoaPods

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#729]

**Comment by Fatme** [comment]
Based on some discussions, I've prepared the expected behavior of the CocoaPods support. 

## Plugin prepare
If the plugin contains `Podfile` in `platforms/ios` folder {N} CLI will copy the content of Podfile to `platforms/ios/Podfile` in native project.

After all plugins are being prepared, {N} CLI will call `pod install` inside native project. This will produce `.xcworkspace` file.

## Build
tns build command will respect the produced .xcworkspace for the current project and will build it.

**Comment by ligaz** [comment]
An alternative approach will be to "extend" the `package.json` of the plugin with `ios` section like this:
```json
{
  "name": "nativescript-http",
  "version": "0.9",
  "nativescript":
    "ios" : {
      "pods" : {
        "AFNetworking" : ">=2.0"
      }
    }
  }
}
```
The benefits of this will be that we will not need a separate file for defining the pods. The down side is that we cannot support complex pod files that have ruby code in them. Also we will have to transform the npm version notation to pod's one.

**Comment by tjvantoll** [comment]
My thought on this is that we should support whatever iOS developers are more comfortable with—which I'm _guessing_ (and just guessing) is a `Podfile` rather than a `package.json` snippet.

My reasoning is that, IMO, only people with at least some iOS experience are going to be writing plugins that use Cocoa Pods, so we should be consistent with what they're comfortable with. Your average web developer doesn't know what a CocoaPod even is, and likely won't be jumping to create {N} plugins that use them.

**Comment by teobugslayer** [comment]
I found this [list](https://github.com/dkhamsing/open-source-ios-apps) of OSS iOS apps. 

It appears that ruby actions are relatively uncommon. But actions like `inhibit_all_warnings!`, `use_frameworks!` and `link_with` are common enough and we may need to design to allow their usage. Thoughts?

**Comment by maknz** [comment]
`use_frameworks!` is definitely important to us, I think. We need to use that in order to have non-framework iOS packages work, such as UICKeyChain.

**Comment by ligaz** [comment]
Thanks all for your input. We will be progressing with the dedicated podfile in the plugin strategy.

**Comment by maknz** [comment]
How will this work for non-plugins, i.e. the main app? Will we keep a Podfile/Podfile.lock in App_Resources, or some-such?

**Comment by Fatme** [comment]
Hi @maknz,

What is the use case to need `Podfile` in your main app?

**Comment by maknz** [comment]
Our app uses the UICKeyChain pod for secure storage on iOS. We keep this in `modules/secure-storage.(ios|android).js` files, but no formalities of a third party module, it's just the JS. At the moment, we use [this guide](https://docs.nativescript.org/runtimes/ios/native-libs/CocoaPods) to use pods.

**Comment by vchimev** [comment]
https://github.com/NativeScript/nativescript-cli/issues/826

**Comment by vchimev** [comment]
Related issue: https://github.com/NativeScript/nativescript-cli/issues/831.
