### ISSUE TITLE
Support xcconfig file from plugin

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#883]
The `.xcconfig` file should be in `platforms/ios` folder of the plugin and will be included into native project's xcconfig file.

**Comment by jasssonpet** [comment]
It turns out that now the CocoaPods xcconfig gets ignored and the build fails.

**Comment by jasssonpet** [comment]
I've moved the nativescript xcconfig to the project, and Cocoapods uses the target xcconfig so everything should work now - https://github.com/NativeScript/ios-runtime/pull/322

**Comment by jasssonpet** [comment]
At the moment there is an issue, that only one plugin with xcconfig is supported. This is because at a given level (target or project), only the last assignment of Xcode flags is preserved. The `$(inherited)` value works only for parent settings, not for previous ones.

This conflicts occur also not only between plugins with xcconfig files, but also with CocoaPods (which uses xcconfig files) and now with the iOS runtime also.

A possible solution is that we merge the build setting flags from all pluginson prepare in a single variable assignment. For example:

plugin-1.xcconfig: `OTHER_LDFLAGS -framework "CoreGraphics"`
plugin-2.xcconfig: `OTHER_LDFLAGS -l"sqlite3"`
build.xcconfig: `OTHER_LDFLAGS -framework "CoreGraphics" -l"sqlite3"`

**Comment by jasssonpet** [comment]
After some more discussion with @fealebenpae we have a new proposal:

Instead of a xcconfig file, each plugin could have a `.json` file that looks something like:
```json
{
  "OTHER_LDFLAGS": "-framework CoreGraphics"
}
```
This would make processing the file easier.

On prepare we should modify the `<APP_NAME>/platforms/ios/<APP_NAME>/build.xcconfig` to look like:
```
OTHER_LDFLAGS _<PLUGIN_NAME> = -framework CoreGraphics
OTHER_LDFLAGS = $(inherited) $(OTHER_LDFLAGS_<PLUGIN_NAME>)
```
The extra variable is in order to make removing plugins safely possible.

@Fatme I would appreciate hearing your thoughts on this.

**Comment by ligaz** [comment]
Isn't it better if we say that the only way to support this is via Cocoapods? If you have a plugin that requires compiler flag changes wrap it in a pod and give it to us.

**Comment by fealebenpae** [comment]
Does CocoaPods support binary-only pods? That is to say, if you only have a static library from a vendor, say TelerikUI, can you wrap that in a pod?

**Comment by ligaz** [comment]
It looks like this according to this [issue](https://github.com/CocoaPods/CocoaPods/pull/224). Also there is support for `vendored_frameworks` and `vendored_libraries` as mentioned in the [Changelog](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md).

**Comment by vchimev** [comment]
Issue 1:
```
VCHIMEVMAC:Work vchimev$ node_modules/.bin/tns plugin add plugin/xcconfig-plugin --path app123
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
xcconfig-plugin@0.0.1 app123/node_modules/xcconfig-plugin
Successfully installed plugin xcconfig-plugin.
VCHIMEVMAC:Work vchimev$ cat app123/package.json 
{
  "nativescript": {
    "id": "org.nativescript.app123",
    "tns-ios": {
      "version": "1.4.1"
    }
  },
  "dependencies": {
    "tns-core-modules": "1.4.0",
    "xcconfig-plugin": "file:plugin/xcconfig-plugin"
  }
}
VCHIMEVMAC:Work vchimev$ 
VCHIMEVMAC:Work vchimev$ 
VCHIMEVMAC:Work vchimev$ node_modules/.bin/tns run ios --path app123
Successfully prepared plugin xcconfig-plugin for ios.
Processing node_modules failed. Error:Error: EISDIR, read

```
