### ISSUE TITLE
tns build --release should add --for-device

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#945]
I ran `tns build ios --release` for the first time today, and I was really surprised to find my .ipa in the `platforms/ios/build/emulator` folder.

If I'm doing a release build, shouldn't it be assumed that I'm building for a device and not emulators?

**Comment by tjvantoll** [comment]
On top of this, currently, `tns build ios --release` does not show me where my .ipa was placed. However, `tns build ios --release --for-device` includes this very helpful message:

```
Results at '/Users/tj/Desktop/Groceries/platforms/ios/build/device/Groceries.ipa'
Project successfully built
```

**Comment by rosen-vladimirov** [comment]
Hi @tjvantoll 

Thanks for the feedback. I totally agree with you that release builds must target devices and we'll have to fix this behavior. I'll have to check why you do not see the path to the .ipa when producing release build. I consider both questions as issues in current implementation, so I've marked this as bug.

Thanks again!

**Comment by tjvantoll** [comment]
Hey @rosen-vladimirov,

Thanks for the response. Just to note I do see the feedback when running `tns build ios --release --for-device`; I only do *not* see the path when I omit `--for-device`—aka  `tns build ios --release`.

**Comment by Mitko-Kerezov** [comment]
Hi @tjvantoll 
We've decided against limiting users and instead sticking with the current behavior where any combination of `--release`, `--debug`, `--for-device` and `--emulator` is possible. Instead we've decided to implement a brand new command for performing publish builds which most probably generate an .xcarchive file and/or and .ipa file for ios. 
Having that in mind the fix was reverted with this https://github.com/NativeScript/nativescript-cli/pull/1166

**Comment by tjvantoll** [comment]
Thanks for the update @Mitko-Kerezov. I like the idea of having a new command because I think it’ll be easier for users to find, so :+1:

**Comment by teobugslayer** [comment]
This will be addressed as part of https://github.com/NativeScript/nativescript-cli/issues/1172 , closing this issue.
