### ISSUE TITLE
Adding support for node 4.*

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#958]
_From @prijindal on September 24, 2015 4:50_

A lot of people are upgrading to the latest node version 4.0 
but nativescript can't be installed on node 4.
Any plans to provide its support for latest version?

_Copied from original issue: NativeScript/NativeScript#813_

**Comment by prijindal** [comment]
It is mainly due to these three dependecies:
bufferutil,
ref,
ref-struct(which uses ref),
utf-8-validate,
ws ( which uses bufferutil)

All of these are using an earlier version of nan (1.5 or 1.8) which does not support node 4.0.0 but nan's latest version 2.0 does

**Comment by azam** [comment]
@rosen-vladimirov et al
Seems like the issue is dropped from 1.4.x milestone, and will only be available on 1.5.x
Do we have to wait for 1.5.x if we only have a node 4.x.x environment?

**Comment by prijindal** [comment]
@azam Yeah it doesn't seem to be working on node 4.0.0
If you want to use it for now you will have to roll back to node 0.12
Try using nvm to manage your node environment

**Comment by azam** [comment]
@rosen-vladimirov marked this issue for 1.4.3 :+1 Hoping for the best

**Comment by rosen-vladimirov** [comment]
Hi guys,
Yes we are trying to include the support for Node 4.2.1+ with our 1.4.3 release. We understand how important is this for your, so we've decided to force the update. We are working on this for a lot of time and we've found several issues with our native dependencies and with the node itself. That's why we needed so much time. Anyway, you should be able to use the incoming 1.4.3 release with node 4.2.1 or later. Please note that you will not be able to use it with node 4.0.0. or node 4.2.0 due to some known issues in the node itself.
We'll be glad to hear back from you once 1.4.3 is out and you try it with node 4.2.1 :)

**Comment by rosen-vladimirov** [comment]
Hey, we've just released NativeScript CLI 1.4.3. You should be able to use it with Node 4.2.1
Feel free to contact us in case you find any problems :)

**Comment by prijindal** [comment]
It is working perfectly with node 5.0.0 too!! :+1:
